// Code generated by ent, DO NOT EDIT.

package ent

import "context"

func (ac *AuthCode) Session(ctx context.Context) (*OAuthSession, error) {
	result, err := ac.Edges.SessionOrErr()
	if IsNotLoaded(err) {
		result, err = ac.QuerySession().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (oat *OAuthAccessToken) Session(ctx context.Context) (*OAuthSession, error) {
	result, err := oat.Edges.SessionOrErr()
	if IsNotLoaded(err) {
		result, err = oat.QuerySession().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (ort *OAuthRefreshToken) Session(ctx context.Context) (*OAuthSession, error) {
	result, err := ort.Edges.SessionOrErr()
	if IsNotLoaded(err) {
		result, err = ort.QuerySession().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (oac *OIDCAuthCode) Session(ctx context.Context) (*OAuthSession, error) {
	result, err := oac.Edges.SessionOrErr()
	if IsNotLoaded(err) {
		result, err = oac.QuerySession().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (pk *PKCE) Session(ctx context.Context) (*OAuthSession, error) {
	result, err := pk.Edges.SessionOrErr()
	if IsNotLoaded(err) {
		result, err = pk.QuerySession().Only(ctx)
	}
	return result, MaskNotFound(err)
}
