// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"

	"entgo.io/contrib/entgql"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/errcode"
	"github.com/koalatea/authserver/server/ent/authcode"
	"github.com/koalatea/authserver/server/ent/cert"
	"github.com/koalatea/authserver/server/ent/denylistedjti"
	"github.com/koalatea/authserver/server/ent/oauthaccesstoken"
	"github.com/koalatea/authserver/server/ent/oauthclient"
	"github.com/koalatea/authserver/server/ent/oauthparrequest"
	"github.com/koalatea/authserver/server/ent/oauthrefreshtoken"
	"github.com/koalatea/authserver/server/ent/oauthsession"
	"github.com/koalatea/authserver/server/ent/oidcauthcode"
	"github.com/koalatea/authserver/server/ent/pkce"
	"github.com/koalatea/authserver/server/ent/publicjwk"
	"github.com/koalatea/authserver/server/ent/publicjwkset"
	"github.com/koalatea/authserver/server/ent/user"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Common entgql types.
type (
	Cursor         = entgql.Cursor[int]
	PageInfo       = entgql.PageInfo[int]
	OrderDirection = entgql.OrderDirection
)

func orderFunc(o OrderDirection, field string) func(*sql.Selector) {
	if o == entgql.OrderDirectionDesc {
		return Desc(field)
	}
	return Asc(field)
}

const errInvalidPagination = "INVALID_PAGINATION"

func validateFirstLast(first, last *int) (err *gqlerror.Error) {
	switch {
	case first != nil && last != nil:
		err = &gqlerror.Error{
			Message: "Passing both `first` and `last` to paginate a connection is not supported.",
		}
	case first != nil && *first < 0:
		err = &gqlerror.Error{
			Message: "`first` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	case last != nil && *last < 0:
		err = &gqlerror.Error{
			Message: "`last` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	}
	return err
}

func collectedField(ctx context.Context, path ...string) *graphql.CollectedField {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return nil
	}
	field := fc.Field
	oc := graphql.GetOperationContext(ctx)
walk:
	for _, name := range path {
		for _, f := range graphql.CollectFields(oc, field.Selections, nil) {
			if f.Alias == name {
				field = f
				continue walk
			}
		}
		return nil
	}
	return &field
}

func hasCollectedField(ctx context.Context, path ...string) bool {
	if graphql.GetFieldContext(ctx) == nil {
		return true
	}
	return collectedField(ctx, path...) != nil
}

const (
	edgesField      = "edges"
	nodeField       = "node"
	pageInfoField   = "pageInfo"
	totalCountField = "totalCount"
)

func paginateLimit(first, last *int) int {
	var limit int
	if first != nil {
		limit = *first + 1
	} else if last != nil {
		limit = *last + 1
	}
	return limit
}

// AuthCodeEdge is the edge representation of AuthCode.
type AuthCodeEdge struct {
	Node   *AuthCode `json:"node"`
	Cursor Cursor    `json:"cursor"`
}

// AuthCodeConnection is the connection containing edges to AuthCode.
type AuthCodeConnection struct {
	Edges      []*AuthCodeEdge `json:"edges"`
	PageInfo   PageInfo        `json:"pageInfo"`
	TotalCount int             `json:"totalCount"`
}

func (c *AuthCodeConnection) build(nodes []*AuthCode, pager *authcodePager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *AuthCode
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *AuthCode {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *AuthCode {
			return nodes[i]
		}
	}
	c.Edges = make([]*AuthCodeEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &AuthCodeEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// AuthCodePaginateOption enables pagination customization.
type AuthCodePaginateOption func(*authcodePager) error

// WithAuthCodeOrder configures pagination ordering.
func WithAuthCodeOrder(order *AuthCodeOrder) AuthCodePaginateOption {
	if order == nil {
		order = DefaultAuthCodeOrder
	}
	o := *order
	return func(pager *authcodePager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultAuthCodeOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithAuthCodeFilter configures pagination filter.
func WithAuthCodeFilter(filter func(*AuthCodeQuery) (*AuthCodeQuery, error)) AuthCodePaginateOption {
	return func(pager *authcodePager) error {
		if filter == nil {
			return errors.New("AuthCodeQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type authcodePager struct {
	reverse bool
	order   *AuthCodeOrder
	filter  func(*AuthCodeQuery) (*AuthCodeQuery, error)
}

func newAuthCodePager(opts []AuthCodePaginateOption, reverse bool) (*authcodePager, error) {
	pager := &authcodePager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultAuthCodeOrder
	}
	return pager, nil
}

func (p *authcodePager) applyFilter(query *AuthCodeQuery) (*AuthCodeQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *authcodePager) toCursor(ac *AuthCode) Cursor {
	return p.order.Field.toCursor(ac)
}

func (p *authcodePager) applyCursors(query *AuthCodeQuery, after, before *Cursor) (*AuthCodeQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultAuthCodeOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *authcodePager) applyOrder(query *AuthCodeQuery) *AuthCodeQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultAuthCodeOrder.Field {
		query = query.Order(DefaultAuthCodeOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *authcodePager) orderExpr(query *AuthCodeQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultAuthCodeOrder.Field {
			b.Comma().Ident(DefaultAuthCodeOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to AuthCode.
func (ac *AuthCodeQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...AuthCodePaginateOption,
) (*AuthCodeConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newAuthCodePager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if ac, err = pager.applyFilter(ac); err != nil {
		return nil, err
	}
	conn := &AuthCodeConnection{Edges: []*AuthCodeEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			c := ac.Clone()
			c.ctx.Fields = nil
			if conn.TotalCount, err = c.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if ac, err = pager.applyCursors(ac, after, before); err != nil {
		return nil, err
	}
	limit := paginateLimit(first, last)
	if limit != 0 {
		ac.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := ac.collectField(ctx, limit == 1, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	ac = pager.applyOrder(ac)
	nodes, err := ac.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// AuthCodeOrderField defines the ordering field of AuthCode.
type AuthCodeOrderField struct {
	// Value extracts the ordering value from the given AuthCode.
	Value    func(*AuthCode) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) authcode.OrderOption
	toCursor func(*AuthCode) Cursor
}

// AuthCodeOrder defines the ordering of AuthCode.
type AuthCodeOrder struct {
	Direction OrderDirection      `json:"direction"`
	Field     *AuthCodeOrderField `json:"field"`
}

// DefaultAuthCodeOrder is the default ordering of AuthCode.
var DefaultAuthCodeOrder = &AuthCodeOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &AuthCodeOrderField{
		Value: func(ac *AuthCode) (ent.Value, error) {
			return ac.ID, nil
		},
		column: authcode.FieldID,
		toTerm: authcode.ByID,
		toCursor: func(ac *AuthCode) Cursor {
			return Cursor{ID: ac.ID}
		},
	},
}

// ToEdge converts AuthCode into AuthCodeEdge.
func (ac *AuthCode) ToEdge(order *AuthCodeOrder) *AuthCodeEdge {
	if order == nil {
		order = DefaultAuthCodeOrder
	}
	return &AuthCodeEdge{
		Node:   ac,
		Cursor: order.Field.toCursor(ac),
	}
}

// CertEdge is the edge representation of Cert.
type CertEdge struct {
	Node   *Cert  `json:"node"`
	Cursor Cursor `json:"cursor"`
}

// CertConnection is the connection containing edges to Cert.
type CertConnection struct {
	Edges      []*CertEdge `json:"edges"`
	PageInfo   PageInfo    `json:"pageInfo"`
	TotalCount int         `json:"totalCount"`
}

func (c *CertConnection) build(nodes []*Cert, pager *certPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *Cert
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Cert {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Cert {
			return nodes[i]
		}
	}
	c.Edges = make([]*CertEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &CertEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// CertPaginateOption enables pagination customization.
type CertPaginateOption func(*certPager) error

// WithCertOrder configures pagination ordering.
func WithCertOrder(order *CertOrder) CertPaginateOption {
	if order == nil {
		order = DefaultCertOrder
	}
	o := *order
	return func(pager *certPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultCertOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithCertFilter configures pagination filter.
func WithCertFilter(filter func(*CertQuery) (*CertQuery, error)) CertPaginateOption {
	return func(pager *certPager) error {
		if filter == nil {
			return errors.New("CertQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type certPager struct {
	reverse bool
	order   *CertOrder
	filter  func(*CertQuery) (*CertQuery, error)
}

func newCertPager(opts []CertPaginateOption, reverse bool) (*certPager, error) {
	pager := &certPager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultCertOrder
	}
	return pager, nil
}

func (p *certPager) applyFilter(query *CertQuery) (*CertQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *certPager) toCursor(c *Cert) Cursor {
	return p.order.Field.toCursor(c)
}

func (p *certPager) applyCursors(query *CertQuery, after, before *Cursor) (*CertQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultCertOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *certPager) applyOrder(query *CertQuery) *CertQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultCertOrder.Field {
		query = query.Order(DefaultCertOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *certPager) orderExpr(query *CertQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultCertOrder.Field {
			b.Comma().Ident(DefaultCertOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to Cert.
func (c *CertQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...CertPaginateOption,
) (*CertConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newCertPager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if c, err = pager.applyFilter(c); err != nil {
		return nil, err
	}
	conn := &CertConnection{Edges: []*CertEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			c := c.Clone()
			c.ctx.Fields = nil
			if conn.TotalCount, err = c.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if c, err = pager.applyCursors(c, after, before); err != nil {
		return nil, err
	}
	limit := paginateLimit(first, last)
	if limit != 0 {
		c.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := c.collectField(ctx, limit == 1, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	c = pager.applyOrder(c)
	nodes, err := c.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// CertOrderField defines the ordering field of Cert.
type CertOrderField struct {
	// Value extracts the ordering value from the given Cert.
	Value    func(*Cert) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) cert.OrderOption
	toCursor func(*Cert) Cursor
}

// CertOrder defines the ordering of Cert.
type CertOrder struct {
	Direction OrderDirection  `json:"direction"`
	Field     *CertOrderField `json:"field"`
}

// DefaultCertOrder is the default ordering of Cert.
var DefaultCertOrder = &CertOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &CertOrderField{
		Value: func(c *Cert) (ent.Value, error) {
			return c.ID, nil
		},
		column: cert.FieldID,
		toTerm: cert.ByID,
		toCursor: func(c *Cert) Cursor {
			return Cursor{ID: c.ID}
		},
	},
}

// ToEdge converts Cert into CertEdge.
func (c *Cert) ToEdge(order *CertOrder) *CertEdge {
	if order == nil {
		order = DefaultCertOrder
	}
	return &CertEdge{
		Node:   c,
		Cursor: order.Field.toCursor(c),
	}
}

// DenyListedJTIEdge is the edge representation of DenyListedJTI.
type DenyListedJTIEdge struct {
	Node   *DenyListedJTI `json:"node"`
	Cursor Cursor         `json:"cursor"`
}

// DenyListedJTIConnection is the connection containing edges to DenyListedJTI.
type DenyListedJTIConnection struct {
	Edges      []*DenyListedJTIEdge `json:"edges"`
	PageInfo   PageInfo             `json:"pageInfo"`
	TotalCount int                  `json:"totalCount"`
}

func (c *DenyListedJTIConnection) build(nodes []*DenyListedJTI, pager *denylistedjtiPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *DenyListedJTI
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *DenyListedJTI {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *DenyListedJTI {
			return nodes[i]
		}
	}
	c.Edges = make([]*DenyListedJTIEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &DenyListedJTIEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// DenyListedJTIPaginateOption enables pagination customization.
type DenyListedJTIPaginateOption func(*denylistedjtiPager) error

// WithDenyListedJTIOrder configures pagination ordering.
func WithDenyListedJTIOrder(order *DenyListedJTIOrder) DenyListedJTIPaginateOption {
	if order == nil {
		order = DefaultDenyListedJTIOrder
	}
	o := *order
	return func(pager *denylistedjtiPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultDenyListedJTIOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithDenyListedJTIFilter configures pagination filter.
func WithDenyListedJTIFilter(filter func(*DenyListedJTIQuery) (*DenyListedJTIQuery, error)) DenyListedJTIPaginateOption {
	return func(pager *denylistedjtiPager) error {
		if filter == nil {
			return errors.New("DenyListedJTIQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type denylistedjtiPager struct {
	reverse bool
	order   *DenyListedJTIOrder
	filter  func(*DenyListedJTIQuery) (*DenyListedJTIQuery, error)
}

func newDenyListedJTIPager(opts []DenyListedJTIPaginateOption, reverse bool) (*denylistedjtiPager, error) {
	pager := &denylistedjtiPager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultDenyListedJTIOrder
	}
	return pager, nil
}

func (p *denylistedjtiPager) applyFilter(query *DenyListedJTIQuery) (*DenyListedJTIQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *denylistedjtiPager) toCursor(dlj *DenyListedJTI) Cursor {
	return p.order.Field.toCursor(dlj)
}

func (p *denylistedjtiPager) applyCursors(query *DenyListedJTIQuery, after, before *Cursor) (*DenyListedJTIQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultDenyListedJTIOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *denylistedjtiPager) applyOrder(query *DenyListedJTIQuery) *DenyListedJTIQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultDenyListedJTIOrder.Field {
		query = query.Order(DefaultDenyListedJTIOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *denylistedjtiPager) orderExpr(query *DenyListedJTIQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultDenyListedJTIOrder.Field {
			b.Comma().Ident(DefaultDenyListedJTIOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to DenyListedJTI.
func (dlj *DenyListedJTIQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...DenyListedJTIPaginateOption,
) (*DenyListedJTIConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newDenyListedJTIPager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if dlj, err = pager.applyFilter(dlj); err != nil {
		return nil, err
	}
	conn := &DenyListedJTIConnection{Edges: []*DenyListedJTIEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			c := dlj.Clone()
			c.ctx.Fields = nil
			if conn.TotalCount, err = c.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if dlj, err = pager.applyCursors(dlj, after, before); err != nil {
		return nil, err
	}
	limit := paginateLimit(first, last)
	if limit != 0 {
		dlj.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := dlj.collectField(ctx, limit == 1, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	dlj = pager.applyOrder(dlj)
	nodes, err := dlj.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// DenyListedJTIOrderField defines the ordering field of DenyListedJTI.
type DenyListedJTIOrderField struct {
	// Value extracts the ordering value from the given DenyListedJTI.
	Value    func(*DenyListedJTI) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) denylistedjti.OrderOption
	toCursor func(*DenyListedJTI) Cursor
}

// DenyListedJTIOrder defines the ordering of DenyListedJTI.
type DenyListedJTIOrder struct {
	Direction OrderDirection           `json:"direction"`
	Field     *DenyListedJTIOrderField `json:"field"`
}

// DefaultDenyListedJTIOrder is the default ordering of DenyListedJTI.
var DefaultDenyListedJTIOrder = &DenyListedJTIOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &DenyListedJTIOrderField{
		Value: func(dlj *DenyListedJTI) (ent.Value, error) {
			return dlj.ID, nil
		},
		column: denylistedjti.FieldID,
		toTerm: denylistedjti.ByID,
		toCursor: func(dlj *DenyListedJTI) Cursor {
			return Cursor{ID: dlj.ID}
		},
	},
}

// ToEdge converts DenyListedJTI into DenyListedJTIEdge.
func (dlj *DenyListedJTI) ToEdge(order *DenyListedJTIOrder) *DenyListedJTIEdge {
	if order == nil {
		order = DefaultDenyListedJTIOrder
	}
	return &DenyListedJTIEdge{
		Node:   dlj,
		Cursor: order.Field.toCursor(dlj),
	}
}

// OAuthAccessTokenEdge is the edge representation of OAuthAccessToken.
type OAuthAccessTokenEdge struct {
	Node   *OAuthAccessToken `json:"node"`
	Cursor Cursor            `json:"cursor"`
}

// OAuthAccessTokenConnection is the connection containing edges to OAuthAccessToken.
type OAuthAccessTokenConnection struct {
	Edges      []*OAuthAccessTokenEdge `json:"edges"`
	PageInfo   PageInfo                `json:"pageInfo"`
	TotalCount int                     `json:"totalCount"`
}

func (c *OAuthAccessTokenConnection) build(nodes []*OAuthAccessToken, pager *oauthaccesstokenPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *OAuthAccessToken
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *OAuthAccessToken {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *OAuthAccessToken {
			return nodes[i]
		}
	}
	c.Edges = make([]*OAuthAccessTokenEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &OAuthAccessTokenEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// OAuthAccessTokenPaginateOption enables pagination customization.
type OAuthAccessTokenPaginateOption func(*oauthaccesstokenPager) error

// WithOAuthAccessTokenOrder configures pagination ordering.
func WithOAuthAccessTokenOrder(order *OAuthAccessTokenOrder) OAuthAccessTokenPaginateOption {
	if order == nil {
		order = DefaultOAuthAccessTokenOrder
	}
	o := *order
	return func(pager *oauthaccesstokenPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultOAuthAccessTokenOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithOAuthAccessTokenFilter configures pagination filter.
func WithOAuthAccessTokenFilter(filter func(*OAuthAccessTokenQuery) (*OAuthAccessTokenQuery, error)) OAuthAccessTokenPaginateOption {
	return func(pager *oauthaccesstokenPager) error {
		if filter == nil {
			return errors.New("OAuthAccessTokenQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type oauthaccesstokenPager struct {
	reverse bool
	order   *OAuthAccessTokenOrder
	filter  func(*OAuthAccessTokenQuery) (*OAuthAccessTokenQuery, error)
}

func newOAuthAccessTokenPager(opts []OAuthAccessTokenPaginateOption, reverse bool) (*oauthaccesstokenPager, error) {
	pager := &oauthaccesstokenPager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultOAuthAccessTokenOrder
	}
	return pager, nil
}

func (p *oauthaccesstokenPager) applyFilter(query *OAuthAccessTokenQuery) (*OAuthAccessTokenQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *oauthaccesstokenPager) toCursor(oat *OAuthAccessToken) Cursor {
	return p.order.Field.toCursor(oat)
}

func (p *oauthaccesstokenPager) applyCursors(query *OAuthAccessTokenQuery, after, before *Cursor) (*OAuthAccessTokenQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultOAuthAccessTokenOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *oauthaccesstokenPager) applyOrder(query *OAuthAccessTokenQuery) *OAuthAccessTokenQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultOAuthAccessTokenOrder.Field {
		query = query.Order(DefaultOAuthAccessTokenOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *oauthaccesstokenPager) orderExpr(query *OAuthAccessTokenQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultOAuthAccessTokenOrder.Field {
			b.Comma().Ident(DefaultOAuthAccessTokenOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to OAuthAccessToken.
func (oat *OAuthAccessTokenQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...OAuthAccessTokenPaginateOption,
) (*OAuthAccessTokenConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newOAuthAccessTokenPager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if oat, err = pager.applyFilter(oat); err != nil {
		return nil, err
	}
	conn := &OAuthAccessTokenConnection{Edges: []*OAuthAccessTokenEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			c := oat.Clone()
			c.ctx.Fields = nil
			if conn.TotalCount, err = c.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if oat, err = pager.applyCursors(oat, after, before); err != nil {
		return nil, err
	}
	limit := paginateLimit(first, last)
	if limit != 0 {
		oat.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := oat.collectField(ctx, limit == 1, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	oat = pager.applyOrder(oat)
	nodes, err := oat.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// OAuthAccessTokenOrderField defines the ordering field of OAuthAccessToken.
type OAuthAccessTokenOrderField struct {
	// Value extracts the ordering value from the given OAuthAccessToken.
	Value    func(*OAuthAccessToken) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) oauthaccesstoken.OrderOption
	toCursor func(*OAuthAccessToken) Cursor
}

// OAuthAccessTokenOrder defines the ordering of OAuthAccessToken.
type OAuthAccessTokenOrder struct {
	Direction OrderDirection              `json:"direction"`
	Field     *OAuthAccessTokenOrderField `json:"field"`
}

// DefaultOAuthAccessTokenOrder is the default ordering of OAuthAccessToken.
var DefaultOAuthAccessTokenOrder = &OAuthAccessTokenOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &OAuthAccessTokenOrderField{
		Value: func(oat *OAuthAccessToken) (ent.Value, error) {
			return oat.ID, nil
		},
		column: oauthaccesstoken.FieldID,
		toTerm: oauthaccesstoken.ByID,
		toCursor: func(oat *OAuthAccessToken) Cursor {
			return Cursor{ID: oat.ID}
		},
	},
}

// ToEdge converts OAuthAccessToken into OAuthAccessTokenEdge.
func (oat *OAuthAccessToken) ToEdge(order *OAuthAccessTokenOrder) *OAuthAccessTokenEdge {
	if order == nil {
		order = DefaultOAuthAccessTokenOrder
	}
	return &OAuthAccessTokenEdge{
		Node:   oat,
		Cursor: order.Field.toCursor(oat),
	}
}

// OAuthClientEdge is the edge representation of OAuthClient.
type OAuthClientEdge struct {
	Node   *OAuthClient `json:"node"`
	Cursor Cursor       `json:"cursor"`
}

// OAuthClientConnection is the connection containing edges to OAuthClient.
type OAuthClientConnection struct {
	Edges      []*OAuthClientEdge `json:"edges"`
	PageInfo   PageInfo           `json:"pageInfo"`
	TotalCount int                `json:"totalCount"`
}

func (c *OAuthClientConnection) build(nodes []*OAuthClient, pager *oauthclientPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *OAuthClient
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *OAuthClient {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *OAuthClient {
			return nodes[i]
		}
	}
	c.Edges = make([]*OAuthClientEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &OAuthClientEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// OAuthClientPaginateOption enables pagination customization.
type OAuthClientPaginateOption func(*oauthclientPager) error

// WithOAuthClientOrder configures pagination ordering.
func WithOAuthClientOrder(order *OAuthClientOrder) OAuthClientPaginateOption {
	if order == nil {
		order = DefaultOAuthClientOrder
	}
	o := *order
	return func(pager *oauthclientPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultOAuthClientOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithOAuthClientFilter configures pagination filter.
func WithOAuthClientFilter(filter func(*OAuthClientQuery) (*OAuthClientQuery, error)) OAuthClientPaginateOption {
	return func(pager *oauthclientPager) error {
		if filter == nil {
			return errors.New("OAuthClientQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type oauthclientPager struct {
	reverse bool
	order   *OAuthClientOrder
	filter  func(*OAuthClientQuery) (*OAuthClientQuery, error)
}

func newOAuthClientPager(opts []OAuthClientPaginateOption, reverse bool) (*oauthclientPager, error) {
	pager := &oauthclientPager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultOAuthClientOrder
	}
	return pager, nil
}

func (p *oauthclientPager) applyFilter(query *OAuthClientQuery) (*OAuthClientQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *oauthclientPager) toCursor(oc *OAuthClient) Cursor {
	return p.order.Field.toCursor(oc)
}

func (p *oauthclientPager) applyCursors(query *OAuthClientQuery, after, before *Cursor) (*OAuthClientQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultOAuthClientOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *oauthclientPager) applyOrder(query *OAuthClientQuery) *OAuthClientQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultOAuthClientOrder.Field {
		query = query.Order(DefaultOAuthClientOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *oauthclientPager) orderExpr(query *OAuthClientQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultOAuthClientOrder.Field {
			b.Comma().Ident(DefaultOAuthClientOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to OAuthClient.
func (oc *OAuthClientQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...OAuthClientPaginateOption,
) (*OAuthClientConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newOAuthClientPager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if oc, err = pager.applyFilter(oc); err != nil {
		return nil, err
	}
	conn := &OAuthClientConnection{Edges: []*OAuthClientEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			c := oc.Clone()
			c.ctx.Fields = nil
			if conn.TotalCount, err = c.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if oc, err = pager.applyCursors(oc, after, before); err != nil {
		return nil, err
	}
	limit := paginateLimit(first, last)
	if limit != 0 {
		oc.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := oc.collectField(ctx, limit == 1, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	oc = pager.applyOrder(oc)
	nodes, err := oc.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// OAuthClientOrderField defines the ordering field of OAuthClient.
type OAuthClientOrderField struct {
	// Value extracts the ordering value from the given OAuthClient.
	Value    func(*OAuthClient) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) oauthclient.OrderOption
	toCursor func(*OAuthClient) Cursor
}

// OAuthClientOrder defines the ordering of OAuthClient.
type OAuthClientOrder struct {
	Direction OrderDirection         `json:"direction"`
	Field     *OAuthClientOrderField `json:"field"`
}

// DefaultOAuthClientOrder is the default ordering of OAuthClient.
var DefaultOAuthClientOrder = &OAuthClientOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &OAuthClientOrderField{
		Value: func(oc *OAuthClient) (ent.Value, error) {
			return oc.ID, nil
		},
		column: oauthclient.FieldID,
		toTerm: oauthclient.ByID,
		toCursor: func(oc *OAuthClient) Cursor {
			return Cursor{ID: oc.ID}
		},
	},
}

// ToEdge converts OAuthClient into OAuthClientEdge.
func (oc *OAuthClient) ToEdge(order *OAuthClientOrder) *OAuthClientEdge {
	if order == nil {
		order = DefaultOAuthClientOrder
	}
	return &OAuthClientEdge{
		Node:   oc,
		Cursor: order.Field.toCursor(oc),
	}
}

// OAuthPARRequestEdge is the edge representation of OAuthPARRequest.
type OAuthPARRequestEdge struct {
	Node   *OAuthPARRequest `json:"node"`
	Cursor Cursor           `json:"cursor"`
}

// OAuthPARRequestConnection is the connection containing edges to OAuthPARRequest.
type OAuthPARRequestConnection struct {
	Edges      []*OAuthPARRequestEdge `json:"edges"`
	PageInfo   PageInfo               `json:"pageInfo"`
	TotalCount int                    `json:"totalCount"`
}

func (c *OAuthPARRequestConnection) build(nodes []*OAuthPARRequest, pager *oauthparrequestPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *OAuthPARRequest
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *OAuthPARRequest {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *OAuthPARRequest {
			return nodes[i]
		}
	}
	c.Edges = make([]*OAuthPARRequestEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &OAuthPARRequestEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// OAuthPARRequestPaginateOption enables pagination customization.
type OAuthPARRequestPaginateOption func(*oauthparrequestPager) error

// WithOAuthPARRequestOrder configures pagination ordering.
func WithOAuthPARRequestOrder(order *OAuthPARRequestOrder) OAuthPARRequestPaginateOption {
	if order == nil {
		order = DefaultOAuthPARRequestOrder
	}
	o := *order
	return func(pager *oauthparrequestPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultOAuthPARRequestOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithOAuthPARRequestFilter configures pagination filter.
func WithOAuthPARRequestFilter(filter func(*OAuthPARRequestQuery) (*OAuthPARRequestQuery, error)) OAuthPARRequestPaginateOption {
	return func(pager *oauthparrequestPager) error {
		if filter == nil {
			return errors.New("OAuthPARRequestQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type oauthparrequestPager struct {
	reverse bool
	order   *OAuthPARRequestOrder
	filter  func(*OAuthPARRequestQuery) (*OAuthPARRequestQuery, error)
}

func newOAuthPARRequestPager(opts []OAuthPARRequestPaginateOption, reverse bool) (*oauthparrequestPager, error) {
	pager := &oauthparrequestPager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultOAuthPARRequestOrder
	}
	return pager, nil
}

func (p *oauthparrequestPager) applyFilter(query *OAuthPARRequestQuery) (*OAuthPARRequestQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *oauthparrequestPager) toCursor(opr *OAuthPARRequest) Cursor {
	return p.order.Field.toCursor(opr)
}

func (p *oauthparrequestPager) applyCursors(query *OAuthPARRequestQuery, after, before *Cursor) (*OAuthPARRequestQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultOAuthPARRequestOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *oauthparrequestPager) applyOrder(query *OAuthPARRequestQuery) *OAuthPARRequestQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultOAuthPARRequestOrder.Field {
		query = query.Order(DefaultOAuthPARRequestOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *oauthparrequestPager) orderExpr(query *OAuthPARRequestQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultOAuthPARRequestOrder.Field {
			b.Comma().Ident(DefaultOAuthPARRequestOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to OAuthPARRequest.
func (opr *OAuthPARRequestQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...OAuthPARRequestPaginateOption,
) (*OAuthPARRequestConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newOAuthPARRequestPager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if opr, err = pager.applyFilter(opr); err != nil {
		return nil, err
	}
	conn := &OAuthPARRequestConnection{Edges: []*OAuthPARRequestEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			c := opr.Clone()
			c.ctx.Fields = nil
			if conn.TotalCount, err = c.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if opr, err = pager.applyCursors(opr, after, before); err != nil {
		return nil, err
	}
	limit := paginateLimit(first, last)
	if limit != 0 {
		opr.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := opr.collectField(ctx, limit == 1, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	opr = pager.applyOrder(opr)
	nodes, err := opr.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// OAuthPARRequestOrderField defines the ordering field of OAuthPARRequest.
type OAuthPARRequestOrderField struct {
	// Value extracts the ordering value from the given OAuthPARRequest.
	Value    func(*OAuthPARRequest) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) oauthparrequest.OrderOption
	toCursor func(*OAuthPARRequest) Cursor
}

// OAuthPARRequestOrder defines the ordering of OAuthPARRequest.
type OAuthPARRequestOrder struct {
	Direction OrderDirection             `json:"direction"`
	Field     *OAuthPARRequestOrderField `json:"field"`
}

// DefaultOAuthPARRequestOrder is the default ordering of OAuthPARRequest.
var DefaultOAuthPARRequestOrder = &OAuthPARRequestOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &OAuthPARRequestOrderField{
		Value: func(opr *OAuthPARRequest) (ent.Value, error) {
			return opr.ID, nil
		},
		column: oauthparrequest.FieldID,
		toTerm: oauthparrequest.ByID,
		toCursor: func(opr *OAuthPARRequest) Cursor {
			return Cursor{ID: opr.ID}
		},
	},
}

// ToEdge converts OAuthPARRequest into OAuthPARRequestEdge.
func (opr *OAuthPARRequest) ToEdge(order *OAuthPARRequestOrder) *OAuthPARRequestEdge {
	if order == nil {
		order = DefaultOAuthPARRequestOrder
	}
	return &OAuthPARRequestEdge{
		Node:   opr,
		Cursor: order.Field.toCursor(opr),
	}
}

// OAuthRefreshTokenEdge is the edge representation of OAuthRefreshToken.
type OAuthRefreshTokenEdge struct {
	Node   *OAuthRefreshToken `json:"node"`
	Cursor Cursor             `json:"cursor"`
}

// OAuthRefreshTokenConnection is the connection containing edges to OAuthRefreshToken.
type OAuthRefreshTokenConnection struct {
	Edges      []*OAuthRefreshTokenEdge `json:"edges"`
	PageInfo   PageInfo                 `json:"pageInfo"`
	TotalCount int                      `json:"totalCount"`
}

func (c *OAuthRefreshTokenConnection) build(nodes []*OAuthRefreshToken, pager *oauthrefreshtokenPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *OAuthRefreshToken
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *OAuthRefreshToken {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *OAuthRefreshToken {
			return nodes[i]
		}
	}
	c.Edges = make([]*OAuthRefreshTokenEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &OAuthRefreshTokenEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// OAuthRefreshTokenPaginateOption enables pagination customization.
type OAuthRefreshTokenPaginateOption func(*oauthrefreshtokenPager) error

// WithOAuthRefreshTokenOrder configures pagination ordering.
func WithOAuthRefreshTokenOrder(order *OAuthRefreshTokenOrder) OAuthRefreshTokenPaginateOption {
	if order == nil {
		order = DefaultOAuthRefreshTokenOrder
	}
	o := *order
	return func(pager *oauthrefreshtokenPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultOAuthRefreshTokenOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithOAuthRefreshTokenFilter configures pagination filter.
func WithOAuthRefreshTokenFilter(filter func(*OAuthRefreshTokenQuery) (*OAuthRefreshTokenQuery, error)) OAuthRefreshTokenPaginateOption {
	return func(pager *oauthrefreshtokenPager) error {
		if filter == nil {
			return errors.New("OAuthRefreshTokenQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type oauthrefreshtokenPager struct {
	reverse bool
	order   *OAuthRefreshTokenOrder
	filter  func(*OAuthRefreshTokenQuery) (*OAuthRefreshTokenQuery, error)
}

func newOAuthRefreshTokenPager(opts []OAuthRefreshTokenPaginateOption, reverse bool) (*oauthrefreshtokenPager, error) {
	pager := &oauthrefreshtokenPager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultOAuthRefreshTokenOrder
	}
	return pager, nil
}

func (p *oauthrefreshtokenPager) applyFilter(query *OAuthRefreshTokenQuery) (*OAuthRefreshTokenQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *oauthrefreshtokenPager) toCursor(ort *OAuthRefreshToken) Cursor {
	return p.order.Field.toCursor(ort)
}

func (p *oauthrefreshtokenPager) applyCursors(query *OAuthRefreshTokenQuery, after, before *Cursor) (*OAuthRefreshTokenQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultOAuthRefreshTokenOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *oauthrefreshtokenPager) applyOrder(query *OAuthRefreshTokenQuery) *OAuthRefreshTokenQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultOAuthRefreshTokenOrder.Field {
		query = query.Order(DefaultOAuthRefreshTokenOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *oauthrefreshtokenPager) orderExpr(query *OAuthRefreshTokenQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultOAuthRefreshTokenOrder.Field {
			b.Comma().Ident(DefaultOAuthRefreshTokenOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to OAuthRefreshToken.
func (ort *OAuthRefreshTokenQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...OAuthRefreshTokenPaginateOption,
) (*OAuthRefreshTokenConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newOAuthRefreshTokenPager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if ort, err = pager.applyFilter(ort); err != nil {
		return nil, err
	}
	conn := &OAuthRefreshTokenConnection{Edges: []*OAuthRefreshTokenEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			c := ort.Clone()
			c.ctx.Fields = nil
			if conn.TotalCount, err = c.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if ort, err = pager.applyCursors(ort, after, before); err != nil {
		return nil, err
	}
	limit := paginateLimit(first, last)
	if limit != 0 {
		ort.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := ort.collectField(ctx, limit == 1, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	ort = pager.applyOrder(ort)
	nodes, err := ort.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// OAuthRefreshTokenOrderField defines the ordering field of OAuthRefreshToken.
type OAuthRefreshTokenOrderField struct {
	// Value extracts the ordering value from the given OAuthRefreshToken.
	Value    func(*OAuthRefreshToken) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) oauthrefreshtoken.OrderOption
	toCursor func(*OAuthRefreshToken) Cursor
}

// OAuthRefreshTokenOrder defines the ordering of OAuthRefreshToken.
type OAuthRefreshTokenOrder struct {
	Direction OrderDirection               `json:"direction"`
	Field     *OAuthRefreshTokenOrderField `json:"field"`
}

// DefaultOAuthRefreshTokenOrder is the default ordering of OAuthRefreshToken.
var DefaultOAuthRefreshTokenOrder = &OAuthRefreshTokenOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &OAuthRefreshTokenOrderField{
		Value: func(ort *OAuthRefreshToken) (ent.Value, error) {
			return ort.ID, nil
		},
		column: oauthrefreshtoken.FieldID,
		toTerm: oauthrefreshtoken.ByID,
		toCursor: func(ort *OAuthRefreshToken) Cursor {
			return Cursor{ID: ort.ID}
		},
	},
}

// ToEdge converts OAuthRefreshToken into OAuthRefreshTokenEdge.
func (ort *OAuthRefreshToken) ToEdge(order *OAuthRefreshTokenOrder) *OAuthRefreshTokenEdge {
	if order == nil {
		order = DefaultOAuthRefreshTokenOrder
	}
	return &OAuthRefreshTokenEdge{
		Node:   ort,
		Cursor: order.Field.toCursor(ort),
	}
}

// OAuthSessionEdge is the edge representation of OAuthSession.
type OAuthSessionEdge struct {
	Node   *OAuthSession `json:"node"`
	Cursor Cursor        `json:"cursor"`
}

// OAuthSessionConnection is the connection containing edges to OAuthSession.
type OAuthSessionConnection struct {
	Edges      []*OAuthSessionEdge `json:"edges"`
	PageInfo   PageInfo            `json:"pageInfo"`
	TotalCount int                 `json:"totalCount"`
}

func (c *OAuthSessionConnection) build(nodes []*OAuthSession, pager *oauthsessionPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *OAuthSession
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *OAuthSession {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *OAuthSession {
			return nodes[i]
		}
	}
	c.Edges = make([]*OAuthSessionEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &OAuthSessionEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// OAuthSessionPaginateOption enables pagination customization.
type OAuthSessionPaginateOption func(*oauthsessionPager) error

// WithOAuthSessionOrder configures pagination ordering.
func WithOAuthSessionOrder(order *OAuthSessionOrder) OAuthSessionPaginateOption {
	if order == nil {
		order = DefaultOAuthSessionOrder
	}
	o := *order
	return func(pager *oauthsessionPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultOAuthSessionOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithOAuthSessionFilter configures pagination filter.
func WithOAuthSessionFilter(filter func(*OAuthSessionQuery) (*OAuthSessionQuery, error)) OAuthSessionPaginateOption {
	return func(pager *oauthsessionPager) error {
		if filter == nil {
			return errors.New("OAuthSessionQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type oauthsessionPager struct {
	reverse bool
	order   *OAuthSessionOrder
	filter  func(*OAuthSessionQuery) (*OAuthSessionQuery, error)
}

func newOAuthSessionPager(opts []OAuthSessionPaginateOption, reverse bool) (*oauthsessionPager, error) {
	pager := &oauthsessionPager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultOAuthSessionOrder
	}
	return pager, nil
}

func (p *oauthsessionPager) applyFilter(query *OAuthSessionQuery) (*OAuthSessionQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *oauthsessionPager) toCursor(os *OAuthSession) Cursor {
	return p.order.Field.toCursor(os)
}

func (p *oauthsessionPager) applyCursors(query *OAuthSessionQuery, after, before *Cursor) (*OAuthSessionQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultOAuthSessionOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *oauthsessionPager) applyOrder(query *OAuthSessionQuery) *OAuthSessionQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultOAuthSessionOrder.Field {
		query = query.Order(DefaultOAuthSessionOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *oauthsessionPager) orderExpr(query *OAuthSessionQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultOAuthSessionOrder.Field {
			b.Comma().Ident(DefaultOAuthSessionOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to OAuthSession.
func (os *OAuthSessionQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...OAuthSessionPaginateOption,
) (*OAuthSessionConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newOAuthSessionPager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if os, err = pager.applyFilter(os); err != nil {
		return nil, err
	}
	conn := &OAuthSessionConnection{Edges: []*OAuthSessionEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			c := os.Clone()
			c.ctx.Fields = nil
			if conn.TotalCount, err = c.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if os, err = pager.applyCursors(os, after, before); err != nil {
		return nil, err
	}
	limit := paginateLimit(first, last)
	if limit != 0 {
		os.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := os.collectField(ctx, limit == 1, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	os = pager.applyOrder(os)
	nodes, err := os.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// OAuthSessionOrderField defines the ordering field of OAuthSession.
type OAuthSessionOrderField struct {
	// Value extracts the ordering value from the given OAuthSession.
	Value    func(*OAuthSession) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) oauthsession.OrderOption
	toCursor func(*OAuthSession) Cursor
}

// OAuthSessionOrder defines the ordering of OAuthSession.
type OAuthSessionOrder struct {
	Direction OrderDirection          `json:"direction"`
	Field     *OAuthSessionOrderField `json:"field"`
}

// DefaultOAuthSessionOrder is the default ordering of OAuthSession.
var DefaultOAuthSessionOrder = &OAuthSessionOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &OAuthSessionOrderField{
		Value: func(os *OAuthSession) (ent.Value, error) {
			return os.ID, nil
		},
		column: oauthsession.FieldID,
		toTerm: oauthsession.ByID,
		toCursor: func(os *OAuthSession) Cursor {
			return Cursor{ID: os.ID}
		},
	},
}

// ToEdge converts OAuthSession into OAuthSessionEdge.
func (os *OAuthSession) ToEdge(order *OAuthSessionOrder) *OAuthSessionEdge {
	if order == nil {
		order = DefaultOAuthSessionOrder
	}
	return &OAuthSessionEdge{
		Node:   os,
		Cursor: order.Field.toCursor(os),
	}
}

// OIDCAuthCodeEdge is the edge representation of OIDCAuthCode.
type OIDCAuthCodeEdge struct {
	Node   *OIDCAuthCode `json:"node"`
	Cursor Cursor        `json:"cursor"`
}

// OIDCAuthCodeConnection is the connection containing edges to OIDCAuthCode.
type OIDCAuthCodeConnection struct {
	Edges      []*OIDCAuthCodeEdge `json:"edges"`
	PageInfo   PageInfo            `json:"pageInfo"`
	TotalCount int                 `json:"totalCount"`
}

func (c *OIDCAuthCodeConnection) build(nodes []*OIDCAuthCode, pager *oidcauthcodePager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *OIDCAuthCode
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *OIDCAuthCode {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *OIDCAuthCode {
			return nodes[i]
		}
	}
	c.Edges = make([]*OIDCAuthCodeEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &OIDCAuthCodeEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// OIDCAuthCodePaginateOption enables pagination customization.
type OIDCAuthCodePaginateOption func(*oidcauthcodePager) error

// WithOIDCAuthCodeOrder configures pagination ordering.
func WithOIDCAuthCodeOrder(order *OIDCAuthCodeOrder) OIDCAuthCodePaginateOption {
	if order == nil {
		order = DefaultOIDCAuthCodeOrder
	}
	o := *order
	return func(pager *oidcauthcodePager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultOIDCAuthCodeOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithOIDCAuthCodeFilter configures pagination filter.
func WithOIDCAuthCodeFilter(filter func(*OIDCAuthCodeQuery) (*OIDCAuthCodeQuery, error)) OIDCAuthCodePaginateOption {
	return func(pager *oidcauthcodePager) error {
		if filter == nil {
			return errors.New("OIDCAuthCodeQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type oidcauthcodePager struct {
	reverse bool
	order   *OIDCAuthCodeOrder
	filter  func(*OIDCAuthCodeQuery) (*OIDCAuthCodeQuery, error)
}

func newOIDCAuthCodePager(opts []OIDCAuthCodePaginateOption, reverse bool) (*oidcauthcodePager, error) {
	pager := &oidcauthcodePager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultOIDCAuthCodeOrder
	}
	return pager, nil
}

func (p *oidcauthcodePager) applyFilter(query *OIDCAuthCodeQuery) (*OIDCAuthCodeQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *oidcauthcodePager) toCursor(oac *OIDCAuthCode) Cursor {
	return p.order.Field.toCursor(oac)
}

func (p *oidcauthcodePager) applyCursors(query *OIDCAuthCodeQuery, after, before *Cursor) (*OIDCAuthCodeQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultOIDCAuthCodeOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *oidcauthcodePager) applyOrder(query *OIDCAuthCodeQuery) *OIDCAuthCodeQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultOIDCAuthCodeOrder.Field {
		query = query.Order(DefaultOIDCAuthCodeOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *oidcauthcodePager) orderExpr(query *OIDCAuthCodeQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultOIDCAuthCodeOrder.Field {
			b.Comma().Ident(DefaultOIDCAuthCodeOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to OIDCAuthCode.
func (oac *OIDCAuthCodeQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...OIDCAuthCodePaginateOption,
) (*OIDCAuthCodeConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newOIDCAuthCodePager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if oac, err = pager.applyFilter(oac); err != nil {
		return nil, err
	}
	conn := &OIDCAuthCodeConnection{Edges: []*OIDCAuthCodeEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			c := oac.Clone()
			c.ctx.Fields = nil
			if conn.TotalCount, err = c.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if oac, err = pager.applyCursors(oac, after, before); err != nil {
		return nil, err
	}
	limit := paginateLimit(first, last)
	if limit != 0 {
		oac.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := oac.collectField(ctx, limit == 1, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	oac = pager.applyOrder(oac)
	nodes, err := oac.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// OIDCAuthCodeOrderField defines the ordering field of OIDCAuthCode.
type OIDCAuthCodeOrderField struct {
	// Value extracts the ordering value from the given OIDCAuthCode.
	Value    func(*OIDCAuthCode) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) oidcauthcode.OrderOption
	toCursor func(*OIDCAuthCode) Cursor
}

// OIDCAuthCodeOrder defines the ordering of OIDCAuthCode.
type OIDCAuthCodeOrder struct {
	Direction OrderDirection          `json:"direction"`
	Field     *OIDCAuthCodeOrderField `json:"field"`
}

// DefaultOIDCAuthCodeOrder is the default ordering of OIDCAuthCode.
var DefaultOIDCAuthCodeOrder = &OIDCAuthCodeOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &OIDCAuthCodeOrderField{
		Value: func(oac *OIDCAuthCode) (ent.Value, error) {
			return oac.ID, nil
		},
		column: oidcauthcode.FieldID,
		toTerm: oidcauthcode.ByID,
		toCursor: func(oac *OIDCAuthCode) Cursor {
			return Cursor{ID: oac.ID}
		},
	},
}

// ToEdge converts OIDCAuthCode into OIDCAuthCodeEdge.
func (oac *OIDCAuthCode) ToEdge(order *OIDCAuthCodeOrder) *OIDCAuthCodeEdge {
	if order == nil {
		order = DefaultOIDCAuthCodeOrder
	}
	return &OIDCAuthCodeEdge{
		Node:   oac,
		Cursor: order.Field.toCursor(oac),
	}
}

// PKCEEdge is the edge representation of PKCE.
type PKCEEdge struct {
	Node   *PKCE  `json:"node"`
	Cursor Cursor `json:"cursor"`
}

// PKCEConnection is the connection containing edges to PKCE.
type PKCEConnection struct {
	Edges      []*PKCEEdge `json:"edges"`
	PageInfo   PageInfo    `json:"pageInfo"`
	TotalCount int         `json:"totalCount"`
}

func (c *PKCEConnection) build(nodes []*PKCE, pager *pkcePager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *PKCE
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *PKCE {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *PKCE {
			return nodes[i]
		}
	}
	c.Edges = make([]*PKCEEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &PKCEEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// PKCEPaginateOption enables pagination customization.
type PKCEPaginateOption func(*pkcePager) error

// WithPKCEOrder configures pagination ordering.
func WithPKCEOrder(order *PKCEOrder) PKCEPaginateOption {
	if order == nil {
		order = DefaultPKCEOrder
	}
	o := *order
	return func(pager *pkcePager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultPKCEOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithPKCEFilter configures pagination filter.
func WithPKCEFilter(filter func(*PKCEQuery) (*PKCEQuery, error)) PKCEPaginateOption {
	return func(pager *pkcePager) error {
		if filter == nil {
			return errors.New("PKCEQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type pkcePager struct {
	reverse bool
	order   *PKCEOrder
	filter  func(*PKCEQuery) (*PKCEQuery, error)
}

func newPKCEPager(opts []PKCEPaginateOption, reverse bool) (*pkcePager, error) {
	pager := &pkcePager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultPKCEOrder
	}
	return pager, nil
}

func (p *pkcePager) applyFilter(query *PKCEQuery) (*PKCEQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *pkcePager) toCursor(pk *PKCE) Cursor {
	return p.order.Field.toCursor(pk)
}

func (p *pkcePager) applyCursors(query *PKCEQuery, after, before *Cursor) (*PKCEQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultPKCEOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *pkcePager) applyOrder(query *PKCEQuery) *PKCEQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultPKCEOrder.Field {
		query = query.Order(DefaultPKCEOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *pkcePager) orderExpr(query *PKCEQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultPKCEOrder.Field {
			b.Comma().Ident(DefaultPKCEOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to PKCE.
func (pk *PKCEQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...PKCEPaginateOption,
) (*PKCEConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newPKCEPager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if pk, err = pager.applyFilter(pk); err != nil {
		return nil, err
	}
	conn := &PKCEConnection{Edges: []*PKCEEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			c := pk.Clone()
			c.ctx.Fields = nil
			if conn.TotalCount, err = c.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if pk, err = pager.applyCursors(pk, after, before); err != nil {
		return nil, err
	}
	limit := paginateLimit(first, last)
	if limit != 0 {
		pk.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := pk.collectField(ctx, limit == 1, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	pk = pager.applyOrder(pk)
	nodes, err := pk.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// PKCEOrderField defines the ordering field of PKCE.
type PKCEOrderField struct {
	// Value extracts the ordering value from the given PKCE.
	Value    func(*PKCE) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) pkce.OrderOption
	toCursor func(*PKCE) Cursor
}

// PKCEOrder defines the ordering of PKCE.
type PKCEOrder struct {
	Direction OrderDirection  `json:"direction"`
	Field     *PKCEOrderField `json:"field"`
}

// DefaultPKCEOrder is the default ordering of PKCE.
var DefaultPKCEOrder = &PKCEOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &PKCEOrderField{
		Value: func(pk *PKCE) (ent.Value, error) {
			return pk.ID, nil
		},
		column: pkce.FieldID,
		toTerm: pkce.ByID,
		toCursor: func(pk *PKCE) Cursor {
			return Cursor{ID: pk.ID}
		},
	},
}

// ToEdge converts PKCE into PKCEEdge.
func (pk *PKCE) ToEdge(order *PKCEOrder) *PKCEEdge {
	if order == nil {
		order = DefaultPKCEOrder
	}
	return &PKCEEdge{
		Node:   pk,
		Cursor: order.Field.toCursor(pk),
	}
}

// PublicJWKEdge is the edge representation of PublicJWK.
type PublicJWKEdge struct {
	Node   *PublicJWK `json:"node"`
	Cursor Cursor     `json:"cursor"`
}

// PublicJWKConnection is the connection containing edges to PublicJWK.
type PublicJWKConnection struct {
	Edges      []*PublicJWKEdge `json:"edges"`
	PageInfo   PageInfo         `json:"pageInfo"`
	TotalCount int              `json:"totalCount"`
}

func (c *PublicJWKConnection) build(nodes []*PublicJWK, pager *publicjwkPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *PublicJWK
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *PublicJWK {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *PublicJWK {
			return nodes[i]
		}
	}
	c.Edges = make([]*PublicJWKEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &PublicJWKEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// PublicJWKPaginateOption enables pagination customization.
type PublicJWKPaginateOption func(*publicjwkPager) error

// WithPublicJWKOrder configures pagination ordering.
func WithPublicJWKOrder(order *PublicJWKOrder) PublicJWKPaginateOption {
	if order == nil {
		order = DefaultPublicJWKOrder
	}
	o := *order
	return func(pager *publicjwkPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultPublicJWKOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithPublicJWKFilter configures pagination filter.
func WithPublicJWKFilter(filter func(*PublicJWKQuery) (*PublicJWKQuery, error)) PublicJWKPaginateOption {
	return func(pager *publicjwkPager) error {
		if filter == nil {
			return errors.New("PublicJWKQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type publicjwkPager struct {
	reverse bool
	order   *PublicJWKOrder
	filter  func(*PublicJWKQuery) (*PublicJWKQuery, error)
}

func newPublicJWKPager(opts []PublicJWKPaginateOption, reverse bool) (*publicjwkPager, error) {
	pager := &publicjwkPager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultPublicJWKOrder
	}
	return pager, nil
}

func (p *publicjwkPager) applyFilter(query *PublicJWKQuery) (*PublicJWKQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *publicjwkPager) toCursor(pj *PublicJWK) Cursor {
	return p.order.Field.toCursor(pj)
}

func (p *publicjwkPager) applyCursors(query *PublicJWKQuery, after, before *Cursor) (*PublicJWKQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultPublicJWKOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *publicjwkPager) applyOrder(query *PublicJWKQuery) *PublicJWKQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultPublicJWKOrder.Field {
		query = query.Order(DefaultPublicJWKOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *publicjwkPager) orderExpr(query *PublicJWKQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultPublicJWKOrder.Field {
			b.Comma().Ident(DefaultPublicJWKOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to PublicJWK.
func (pj *PublicJWKQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...PublicJWKPaginateOption,
) (*PublicJWKConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newPublicJWKPager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if pj, err = pager.applyFilter(pj); err != nil {
		return nil, err
	}
	conn := &PublicJWKConnection{Edges: []*PublicJWKEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			c := pj.Clone()
			c.ctx.Fields = nil
			if conn.TotalCount, err = c.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if pj, err = pager.applyCursors(pj, after, before); err != nil {
		return nil, err
	}
	limit := paginateLimit(first, last)
	if limit != 0 {
		pj.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := pj.collectField(ctx, limit == 1, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	pj = pager.applyOrder(pj)
	nodes, err := pj.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// PublicJWKOrderField defines the ordering field of PublicJWK.
type PublicJWKOrderField struct {
	// Value extracts the ordering value from the given PublicJWK.
	Value    func(*PublicJWK) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) publicjwk.OrderOption
	toCursor func(*PublicJWK) Cursor
}

// PublicJWKOrder defines the ordering of PublicJWK.
type PublicJWKOrder struct {
	Direction OrderDirection       `json:"direction"`
	Field     *PublicJWKOrderField `json:"field"`
}

// DefaultPublicJWKOrder is the default ordering of PublicJWK.
var DefaultPublicJWKOrder = &PublicJWKOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &PublicJWKOrderField{
		Value: func(pj *PublicJWK) (ent.Value, error) {
			return pj.ID, nil
		},
		column: publicjwk.FieldID,
		toTerm: publicjwk.ByID,
		toCursor: func(pj *PublicJWK) Cursor {
			return Cursor{ID: pj.ID}
		},
	},
}

// ToEdge converts PublicJWK into PublicJWKEdge.
func (pj *PublicJWK) ToEdge(order *PublicJWKOrder) *PublicJWKEdge {
	if order == nil {
		order = DefaultPublicJWKOrder
	}
	return &PublicJWKEdge{
		Node:   pj,
		Cursor: order.Field.toCursor(pj),
	}
}

// PublicJWKSetEdge is the edge representation of PublicJWKSet.
type PublicJWKSetEdge struct {
	Node   *PublicJWKSet `json:"node"`
	Cursor Cursor        `json:"cursor"`
}

// PublicJWKSetConnection is the connection containing edges to PublicJWKSet.
type PublicJWKSetConnection struct {
	Edges      []*PublicJWKSetEdge `json:"edges"`
	PageInfo   PageInfo            `json:"pageInfo"`
	TotalCount int                 `json:"totalCount"`
}

func (c *PublicJWKSetConnection) build(nodes []*PublicJWKSet, pager *publicjwksetPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *PublicJWKSet
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *PublicJWKSet {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *PublicJWKSet {
			return nodes[i]
		}
	}
	c.Edges = make([]*PublicJWKSetEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &PublicJWKSetEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// PublicJWKSetPaginateOption enables pagination customization.
type PublicJWKSetPaginateOption func(*publicjwksetPager) error

// WithPublicJWKSetOrder configures pagination ordering.
func WithPublicJWKSetOrder(order *PublicJWKSetOrder) PublicJWKSetPaginateOption {
	if order == nil {
		order = DefaultPublicJWKSetOrder
	}
	o := *order
	return func(pager *publicjwksetPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultPublicJWKSetOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithPublicJWKSetFilter configures pagination filter.
func WithPublicJWKSetFilter(filter func(*PublicJWKSetQuery) (*PublicJWKSetQuery, error)) PublicJWKSetPaginateOption {
	return func(pager *publicjwksetPager) error {
		if filter == nil {
			return errors.New("PublicJWKSetQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type publicjwksetPager struct {
	reverse bool
	order   *PublicJWKSetOrder
	filter  func(*PublicJWKSetQuery) (*PublicJWKSetQuery, error)
}

func newPublicJWKSetPager(opts []PublicJWKSetPaginateOption, reverse bool) (*publicjwksetPager, error) {
	pager := &publicjwksetPager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultPublicJWKSetOrder
	}
	return pager, nil
}

func (p *publicjwksetPager) applyFilter(query *PublicJWKSetQuery) (*PublicJWKSetQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *publicjwksetPager) toCursor(pjs *PublicJWKSet) Cursor {
	return p.order.Field.toCursor(pjs)
}

func (p *publicjwksetPager) applyCursors(query *PublicJWKSetQuery, after, before *Cursor) (*PublicJWKSetQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultPublicJWKSetOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *publicjwksetPager) applyOrder(query *PublicJWKSetQuery) *PublicJWKSetQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultPublicJWKSetOrder.Field {
		query = query.Order(DefaultPublicJWKSetOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *publicjwksetPager) orderExpr(query *PublicJWKSetQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultPublicJWKSetOrder.Field {
			b.Comma().Ident(DefaultPublicJWKSetOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to PublicJWKSet.
func (pjs *PublicJWKSetQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...PublicJWKSetPaginateOption,
) (*PublicJWKSetConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newPublicJWKSetPager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if pjs, err = pager.applyFilter(pjs); err != nil {
		return nil, err
	}
	conn := &PublicJWKSetConnection{Edges: []*PublicJWKSetEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			c := pjs.Clone()
			c.ctx.Fields = nil
			if conn.TotalCount, err = c.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if pjs, err = pager.applyCursors(pjs, after, before); err != nil {
		return nil, err
	}
	limit := paginateLimit(first, last)
	if limit != 0 {
		pjs.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := pjs.collectField(ctx, limit == 1, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	pjs = pager.applyOrder(pjs)
	nodes, err := pjs.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// PublicJWKSetOrderField defines the ordering field of PublicJWKSet.
type PublicJWKSetOrderField struct {
	// Value extracts the ordering value from the given PublicJWKSet.
	Value    func(*PublicJWKSet) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) publicjwkset.OrderOption
	toCursor func(*PublicJWKSet) Cursor
}

// PublicJWKSetOrder defines the ordering of PublicJWKSet.
type PublicJWKSetOrder struct {
	Direction OrderDirection          `json:"direction"`
	Field     *PublicJWKSetOrderField `json:"field"`
}

// DefaultPublicJWKSetOrder is the default ordering of PublicJWKSet.
var DefaultPublicJWKSetOrder = &PublicJWKSetOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &PublicJWKSetOrderField{
		Value: func(pjs *PublicJWKSet) (ent.Value, error) {
			return pjs.ID, nil
		},
		column: publicjwkset.FieldID,
		toTerm: publicjwkset.ByID,
		toCursor: func(pjs *PublicJWKSet) Cursor {
			return Cursor{ID: pjs.ID}
		},
	},
}

// ToEdge converts PublicJWKSet into PublicJWKSetEdge.
func (pjs *PublicJWKSet) ToEdge(order *PublicJWKSetOrder) *PublicJWKSetEdge {
	if order == nil {
		order = DefaultPublicJWKSetOrder
	}
	return &PublicJWKSetEdge{
		Node:   pjs,
		Cursor: order.Field.toCursor(pjs),
	}
}

// UserEdge is the edge representation of User.
type UserEdge struct {
	Node   *User  `json:"node"`
	Cursor Cursor `json:"cursor"`
}

// UserConnection is the connection containing edges to User.
type UserConnection struct {
	Edges      []*UserEdge `json:"edges"`
	PageInfo   PageInfo    `json:"pageInfo"`
	TotalCount int         `json:"totalCount"`
}

func (c *UserConnection) build(nodes []*User, pager *userPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *User
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *User {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *User {
			return nodes[i]
		}
	}
	c.Edges = make([]*UserEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &UserEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// UserPaginateOption enables pagination customization.
type UserPaginateOption func(*userPager) error

// WithUserOrder configures pagination ordering.
func WithUserOrder(order *UserOrder) UserPaginateOption {
	if order == nil {
		order = DefaultUserOrder
	}
	o := *order
	return func(pager *userPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultUserOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithUserFilter configures pagination filter.
func WithUserFilter(filter func(*UserQuery) (*UserQuery, error)) UserPaginateOption {
	return func(pager *userPager) error {
		if filter == nil {
			return errors.New("UserQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type userPager struct {
	reverse bool
	order   *UserOrder
	filter  func(*UserQuery) (*UserQuery, error)
}

func newUserPager(opts []UserPaginateOption, reverse bool) (*userPager, error) {
	pager := &userPager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultUserOrder
	}
	return pager, nil
}

func (p *userPager) applyFilter(query *UserQuery) (*UserQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *userPager) toCursor(u *User) Cursor {
	return p.order.Field.toCursor(u)
}

func (p *userPager) applyCursors(query *UserQuery, after, before *Cursor) (*UserQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultUserOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *userPager) applyOrder(query *UserQuery) *UserQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultUserOrder.Field {
		query = query.Order(DefaultUserOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *userPager) orderExpr(query *UserQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultUserOrder.Field {
			b.Comma().Ident(DefaultUserOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to User.
func (u *UserQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...UserPaginateOption,
) (*UserConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newUserPager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if u, err = pager.applyFilter(u); err != nil {
		return nil, err
	}
	conn := &UserConnection{Edges: []*UserEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			c := u.Clone()
			c.ctx.Fields = nil
			if conn.TotalCount, err = c.Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if u, err = pager.applyCursors(u, after, before); err != nil {
		return nil, err
	}
	limit := paginateLimit(first, last)
	if limit != 0 {
		u.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := u.collectField(ctx, limit == 1, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	u = pager.applyOrder(u)
	nodes, err := u.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// UserOrderField defines the ordering field of User.
type UserOrderField struct {
	// Value extracts the ordering value from the given User.
	Value    func(*User) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) user.OrderOption
	toCursor func(*User) Cursor
}

// UserOrder defines the ordering of User.
type UserOrder struct {
	Direction OrderDirection  `json:"direction"`
	Field     *UserOrderField `json:"field"`
}

// DefaultUserOrder is the default ordering of User.
var DefaultUserOrder = &UserOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &UserOrderField{
		Value: func(u *User) (ent.Value, error) {
			return u.ID, nil
		},
		column: user.FieldID,
		toTerm: user.ByID,
		toCursor: func(u *User) Cursor {
			return Cursor{ID: u.ID}
		},
	},
}

// ToEdge converts User into UserEdge.
func (u *User) ToEdge(order *UserOrder) *UserEdge {
	if order == nil {
		order = DefaultUserOrder
	}
	return &UserEdge{
		Node:   u,
		Cursor: order.Field.toCursor(u),
	}
}
