// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/koalatea/authserver/server/ent/oauthparrequest"
)

// OAuthPARRequestCreate is the builder for creating a OAuthPARRequest entity.
type OAuthPARRequestCreate struct {
	config
	mutation *OAuthPARRequestMutation
	hooks    []Hook
}

// SetRequest sets the "request" field.
func (oprc *OAuthPARRequestCreate) SetRequest(s string) *OAuthPARRequestCreate {
	oprc.mutation.SetRequest(s)
	return oprc
}

// Mutation returns the OAuthPARRequestMutation object of the builder.
func (oprc *OAuthPARRequestCreate) Mutation() *OAuthPARRequestMutation {
	return oprc.mutation
}

// Save creates the OAuthPARRequest in the database.
func (oprc *OAuthPARRequestCreate) Save(ctx context.Context) (*OAuthPARRequest, error) {
	var (
		err  error
		node *OAuthPARRequest
	)
	if len(oprc.hooks) == 0 {
		if err = oprc.check(); err != nil {
			return nil, err
		}
		node, err = oprc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OAuthPARRequestMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = oprc.check(); err != nil {
				return nil, err
			}
			oprc.mutation = mutation
			if node, err = oprc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(oprc.hooks) - 1; i >= 0; i-- {
			if oprc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = oprc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, oprc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*OAuthPARRequest)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from OAuthPARRequestMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (oprc *OAuthPARRequestCreate) SaveX(ctx context.Context) *OAuthPARRequest {
	v, err := oprc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (oprc *OAuthPARRequestCreate) Exec(ctx context.Context) error {
	_, err := oprc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oprc *OAuthPARRequestCreate) ExecX(ctx context.Context) {
	if err := oprc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (oprc *OAuthPARRequestCreate) check() error {
	if _, ok := oprc.mutation.Request(); !ok {
		return &ValidationError{Name: "request", err: errors.New(`ent: missing required field "OAuthPARRequest.request"`)}
	}
	return nil
}

func (oprc *OAuthPARRequestCreate) sqlSave(ctx context.Context) (*OAuthPARRequest, error) {
	_node, _spec := oprc.createSpec()
	if err := sqlgraph.CreateNode(ctx, oprc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (oprc *OAuthPARRequestCreate) createSpec() (*OAuthPARRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthPARRequest{config: oprc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: oauthparrequest.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: oauthparrequest.FieldID,
			},
		}
	)
	if value, ok := oprc.mutation.Request(); ok {
		_spec.SetField(oauthparrequest.FieldRequest, field.TypeString, value)
		_node.Request = value
	}
	return _node, _spec
}

// OAuthPARRequestCreateBulk is the builder for creating many OAuthPARRequest entities in bulk.
type OAuthPARRequestCreateBulk struct {
	config
	builders []*OAuthPARRequestCreate
}

// Save creates the OAuthPARRequest entities in the database.
func (oprcb *OAuthPARRequestCreateBulk) Save(ctx context.Context) ([]*OAuthPARRequest, error) {
	specs := make([]*sqlgraph.CreateSpec, len(oprcb.builders))
	nodes := make([]*OAuthPARRequest, len(oprcb.builders))
	mutators := make([]Mutator, len(oprcb.builders))
	for i := range oprcb.builders {
		func(i int, root context.Context) {
			builder := oprcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthPARRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, oprcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, oprcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, oprcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (oprcb *OAuthPARRequestCreateBulk) SaveX(ctx context.Context) []*OAuthPARRequest {
	v, err := oprcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (oprcb *OAuthPARRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := oprcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oprcb *OAuthPARRequestCreateBulk) ExecX(ctx context.Context) {
	if err := oprcb.Exec(ctx); err != nil {
		panic(err)
	}
}
