// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/koalatea/authserver/server/ent/oauthaccesstoken"
	"github.com/koalatea/authserver/server/ent/oauthsession"
)

// OAuthAccessTokenCreate is the builder for creating a OAuthAccessToken entity.
type OAuthAccessTokenCreate struct {
	config
	mutation *OAuthAccessTokenMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSignature sets the "signature" field.
func (oatc *OAuthAccessTokenCreate) SetSignature(s string) *OAuthAccessTokenCreate {
	oatc.mutation.SetSignature(s)
	return oatc
}

// SetSessionID sets the "session" edge to the OAuthSession entity by ID.
func (oatc *OAuthAccessTokenCreate) SetSessionID(id int) *OAuthAccessTokenCreate {
	oatc.mutation.SetSessionID(id)
	return oatc
}

// SetNillableSessionID sets the "session" edge to the OAuthSession entity by ID if the given value is not nil.
func (oatc *OAuthAccessTokenCreate) SetNillableSessionID(id *int) *OAuthAccessTokenCreate {
	if id != nil {
		oatc = oatc.SetSessionID(*id)
	}
	return oatc
}

// SetSession sets the "session" edge to the OAuthSession entity.
func (oatc *OAuthAccessTokenCreate) SetSession(o *OAuthSession) *OAuthAccessTokenCreate {
	return oatc.SetSessionID(o.ID)
}

// Mutation returns the OAuthAccessTokenMutation object of the builder.
func (oatc *OAuthAccessTokenCreate) Mutation() *OAuthAccessTokenMutation {
	return oatc.mutation
}

// Save creates the OAuthAccessToken in the database.
func (oatc *OAuthAccessTokenCreate) Save(ctx context.Context) (*OAuthAccessToken, error) {
	return withHooks(ctx, oatc.sqlSave, oatc.mutation, oatc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (oatc *OAuthAccessTokenCreate) SaveX(ctx context.Context) *OAuthAccessToken {
	v, err := oatc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (oatc *OAuthAccessTokenCreate) Exec(ctx context.Context) error {
	_, err := oatc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oatc *OAuthAccessTokenCreate) ExecX(ctx context.Context) {
	if err := oatc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (oatc *OAuthAccessTokenCreate) check() error {
	if _, ok := oatc.mutation.Signature(); !ok {
		return &ValidationError{Name: "signature", err: errors.New(`ent: missing required field "OAuthAccessToken.signature"`)}
	}
	return nil
}

func (oatc *OAuthAccessTokenCreate) sqlSave(ctx context.Context) (*OAuthAccessToken, error) {
	if err := oatc.check(); err != nil {
		return nil, err
	}
	_node, _spec := oatc.createSpec()
	if err := sqlgraph.CreateNode(ctx, oatc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	oatc.mutation.id = &_node.ID
	oatc.mutation.done = true
	return _node, nil
}

func (oatc *OAuthAccessTokenCreate) createSpec() (*OAuthAccessToken, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthAccessToken{config: oatc.config}
		_spec = sqlgraph.NewCreateSpec(oauthaccesstoken.Table, sqlgraph.NewFieldSpec(oauthaccesstoken.FieldID, field.TypeInt))
	)
	_spec.OnConflict = oatc.conflict
	if value, ok := oatc.mutation.Signature(); ok {
		_spec.SetField(oauthaccesstoken.FieldSignature, field.TypeString, value)
		_node.Signature = value
	}
	if nodes := oatc.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   oauthaccesstoken.SessionTable,
			Columns: []string{oauthaccesstoken.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthsession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.oauth_access_token_session = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthAccessToken.Create().
//		SetSignature(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthAccessTokenUpsert) {
//			SetSignature(v+v).
//		}).
//		Exec(ctx)
func (oatc *OAuthAccessTokenCreate) OnConflict(opts ...sql.ConflictOption) *OAuthAccessTokenUpsertOne {
	oatc.conflict = opts
	return &OAuthAccessTokenUpsertOne{
		create: oatc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthAccessToken.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (oatc *OAuthAccessTokenCreate) OnConflictColumns(columns ...string) *OAuthAccessTokenUpsertOne {
	oatc.conflict = append(oatc.conflict, sql.ConflictColumns(columns...))
	return &OAuthAccessTokenUpsertOne{
		create: oatc,
	}
}

type (
	// OAuthAccessTokenUpsertOne is the builder for "upsert"-ing
	//  one OAuthAccessToken node.
	OAuthAccessTokenUpsertOne struct {
		create *OAuthAccessTokenCreate
	}

	// OAuthAccessTokenUpsert is the "OnConflict" setter.
	OAuthAccessTokenUpsert struct {
		*sql.UpdateSet
	}
)

// SetSignature sets the "signature" field.
func (u *OAuthAccessTokenUpsert) SetSignature(v string) *OAuthAccessTokenUpsert {
	u.Set(oauthaccesstoken.FieldSignature, v)
	return u
}

// UpdateSignature sets the "signature" field to the value that was provided on create.
func (u *OAuthAccessTokenUpsert) UpdateSignature() *OAuthAccessTokenUpsert {
	u.SetExcluded(oauthaccesstoken.FieldSignature)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OAuthAccessToken.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthAccessTokenUpsertOne) UpdateNewValues() *OAuthAccessTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthAccessToken.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OAuthAccessTokenUpsertOne) Ignore() *OAuthAccessTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthAccessTokenUpsertOne) DoNothing() *OAuthAccessTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthAccessTokenCreate.OnConflict
// documentation for more info.
func (u *OAuthAccessTokenUpsertOne) Update(set func(*OAuthAccessTokenUpsert)) *OAuthAccessTokenUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthAccessTokenUpsert{UpdateSet: update})
	}))
	return u
}

// SetSignature sets the "signature" field.
func (u *OAuthAccessTokenUpsertOne) SetSignature(v string) *OAuthAccessTokenUpsertOne {
	return u.Update(func(s *OAuthAccessTokenUpsert) {
		s.SetSignature(v)
	})
}

// UpdateSignature sets the "signature" field to the value that was provided on create.
func (u *OAuthAccessTokenUpsertOne) UpdateSignature() *OAuthAccessTokenUpsertOne {
	return u.Update(func(s *OAuthAccessTokenUpsert) {
		s.UpdateSignature()
	})
}

// Exec executes the query.
func (u *OAuthAccessTokenUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthAccessTokenCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthAccessTokenUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OAuthAccessTokenUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OAuthAccessTokenUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OAuthAccessTokenCreateBulk is the builder for creating many OAuthAccessToken entities in bulk.
type OAuthAccessTokenCreateBulk struct {
	config
	err      error
	builders []*OAuthAccessTokenCreate
	conflict []sql.ConflictOption
}

// Save creates the OAuthAccessToken entities in the database.
func (oatcb *OAuthAccessTokenCreateBulk) Save(ctx context.Context) ([]*OAuthAccessToken, error) {
	if oatcb.err != nil {
		return nil, oatcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(oatcb.builders))
	nodes := make([]*OAuthAccessToken, len(oatcb.builders))
	mutators := make([]Mutator, len(oatcb.builders))
	for i := range oatcb.builders {
		func(i int, root context.Context) {
			builder := oatcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthAccessTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, oatcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = oatcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, oatcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, oatcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (oatcb *OAuthAccessTokenCreateBulk) SaveX(ctx context.Context) []*OAuthAccessToken {
	v, err := oatcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (oatcb *OAuthAccessTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := oatcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oatcb *OAuthAccessTokenCreateBulk) ExecX(ctx context.Context) {
	if err := oatcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthAccessToken.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthAccessTokenUpsert) {
//			SetSignature(v+v).
//		}).
//		Exec(ctx)
func (oatcb *OAuthAccessTokenCreateBulk) OnConflict(opts ...sql.ConflictOption) *OAuthAccessTokenUpsertBulk {
	oatcb.conflict = opts
	return &OAuthAccessTokenUpsertBulk{
		create: oatcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthAccessToken.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (oatcb *OAuthAccessTokenCreateBulk) OnConflictColumns(columns ...string) *OAuthAccessTokenUpsertBulk {
	oatcb.conflict = append(oatcb.conflict, sql.ConflictColumns(columns...))
	return &OAuthAccessTokenUpsertBulk{
		create: oatcb,
	}
}

// OAuthAccessTokenUpsertBulk is the builder for "upsert"-ing
// a bulk of OAuthAccessToken nodes.
type OAuthAccessTokenUpsertBulk struct {
	create *OAuthAccessTokenCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OAuthAccessToken.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthAccessTokenUpsertBulk) UpdateNewValues() *OAuthAccessTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthAccessToken.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OAuthAccessTokenUpsertBulk) Ignore() *OAuthAccessTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthAccessTokenUpsertBulk) DoNothing() *OAuthAccessTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthAccessTokenCreateBulk.OnConflict
// documentation for more info.
func (u *OAuthAccessTokenUpsertBulk) Update(set func(*OAuthAccessTokenUpsert)) *OAuthAccessTokenUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthAccessTokenUpsert{UpdateSet: update})
	}))
	return u
}

// SetSignature sets the "signature" field.
func (u *OAuthAccessTokenUpsertBulk) SetSignature(v string) *OAuthAccessTokenUpsertBulk {
	return u.Update(func(s *OAuthAccessTokenUpsert) {
		s.SetSignature(v)
	})
}

// UpdateSignature sets the "signature" field to the value that was provided on create.
func (u *OAuthAccessTokenUpsertBulk) UpdateSignature() *OAuthAccessTokenUpsertBulk {
	return u.Update(func(s *OAuthAccessTokenUpsert) {
		s.UpdateSignature()
	})
}

// Exec executes the query.
func (u *OAuthAccessTokenUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OAuthAccessTokenCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthAccessTokenCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthAccessTokenUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
