// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/koalatea/authserver/server/ent/oauthaccesstoken"
	"github.com/koalatea/authserver/server/ent/oauthsession"
	"github.com/koalatea/authserver/server/ent/predicate"
)

// OAuthAccessTokenQuery is the builder for querying OAuthAccessToken entities.
type OAuthAccessTokenQuery struct {
	config
	ctx         *QueryContext
	order       []oauthaccesstoken.OrderOption
	inters      []Interceptor
	predicates  []predicate.OAuthAccessToken
	withSession *OAuthSessionQuery
	withFKs     bool
	modifiers   []func(*sql.Selector)
	loadTotal   []func(context.Context, []*OAuthAccessToken) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OAuthAccessTokenQuery builder.
func (oatq *OAuthAccessTokenQuery) Where(ps ...predicate.OAuthAccessToken) *OAuthAccessTokenQuery {
	oatq.predicates = append(oatq.predicates, ps...)
	return oatq
}

// Limit the number of records to be returned by this query.
func (oatq *OAuthAccessTokenQuery) Limit(limit int) *OAuthAccessTokenQuery {
	oatq.ctx.Limit = &limit
	return oatq
}

// Offset to start from.
func (oatq *OAuthAccessTokenQuery) Offset(offset int) *OAuthAccessTokenQuery {
	oatq.ctx.Offset = &offset
	return oatq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (oatq *OAuthAccessTokenQuery) Unique(unique bool) *OAuthAccessTokenQuery {
	oatq.ctx.Unique = &unique
	return oatq
}

// Order specifies how the records should be ordered.
func (oatq *OAuthAccessTokenQuery) Order(o ...oauthaccesstoken.OrderOption) *OAuthAccessTokenQuery {
	oatq.order = append(oatq.order, o...)
	return oatq
}

// QuerySession chains the current query on the "session" edge.
func (oatq *OAuthAccessTokenQuery) QuerySession() *OAuthSessionQuery {
	query := (&OAuthSessionClient{config: oatq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := oatq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := oatq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(oauthaccesstoken.Table, oauthaccesstoken.FieldID, selector),
			sqlgraph.To(oauthsession.Table, oauthsession.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, oauthaccesstoken.SessionTable, oauthaccesstoken.SessionColumn),
		)
		fromU = sqlgraph.SetNeighbors(oatq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first OAuthAccessToken entity from the query.
// Returns a *NotFoundError when no OAuthAccessToken was found.
func (oatq *OAuthAccessTokenQuery) First(ctx context.Context) (*OAuthAccessToken, error) {
	nodes, err := oatq.Limit(1).All(setContextOp(ctx, oatq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{oauthaccesstoken.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (oatq *OAuthAccessTokenQuery) FirstX(ctx context.Context) *OAuthAccessToken {
	node, err := oatq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OAuthAccessToken ID from the query.
// Returns a *NotFoundError when no OAuthAccessToken ID was found.
func (oatq *OAuthAccessTokenQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = oatq.Limit(1).IDs(setContextOp(ctx, oatq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{oauthaccesstoken.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (oatq *OAuthAccessTokenQuery) FirstIDX(ctx context.Context) int {
	id, err := oatq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OAuthAccessToken entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OAuthAccessToken entity is found.
// Returns a *NotFoundError when no OAuthAccessToken entities are found.
func (oatq *OAuthAccessTokenQuery) Only(ctx context.Context) (*OAuthAccessToken, error) {
	nodes, err := oatq.Limit(2).All(setContextOp(ctx, oatq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{oauthaccesstoken.Label}
	default:
		return nil, &NotSingularError{oauthaccesstoken.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (oatq *OAuthAccessTokenQuery) OnlyX(ctx context.Context) *OAuthAccessToken {
	node, err := oatq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OAuthAccessToken ID in the query.
// Returns a *NotSingularError when more than one OAuthAccessToken ID is found.
// Returns a *NotFoundError when no entities are found.
func (oatq *OAuthAccessTokenQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = oatq.Limit(2).IDs(setContextOp(ctx, oatq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{oauthaccesstoken.Label}
	default:
		err = &NotSingularError{oauthaccesstoken.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (oatq *OAuthAccessTokenQuery) OnlyIDX(ctx context.Context) int {
	id, err := oatq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OAuthAccessTokens.
func (oatq *OAuthAccessTokenQuery) All(ctx context.Context) ([]*OAuthAccessToken, error) {
	ctx = setContextOp(ctx, oatq.ctx, "All")
	if err := oatq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OAuthAccessToken, *OAuthAccessTokenQuery]()
	return withInterceptors[[]*OAuthAccessToken](ctx, oatq, qr, oatq.inters)
}

// AllX is like All, but panics if an error occurs.
func (oatq *OAuthAccessTokenQuery) AllX(ctx context.Context) []*OAuthAccessToken {
	nodes, err := oatq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OAuthAccessToken IDs.
func (oatq *OAuthAccessTokenQuery) IDs(ctx context.Context) (ids []int, err error) {
	if oatq.ctx.Unique == nil && oatq.path != nil {
		oatq.Unique(true)
	}
	ctx = setContextOp(ctx, oatq.ctx, "IDs")
	if err = oatq.Select(oauthaccesstoken.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (oatq *OAuthAccessTokenQuery) IDsX(ctx context.Context) []int {
	ids, err := oatq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (oatq *OAuthAccessTokenQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, oatq.ctx, "Count")
	if err := oatq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, oatq, querierCount[*OAuthAccessTokenQuery](), oatq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (oatq *OAuthAccessTokenQuery) CountX(ctx context.Context) int {
	count, err := oatq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (oatq *OAuthAccessTokenQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, oatq.ctx, "Exist")
	switch _, err := oatq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (oatq *OAuthAccessTokenQuery) ExistX(ctx context.Context) bool {
	exist, err := oatq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OAuthAccessTokenQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (oatq *OAuthAccessTokenQuery) Clone() *OAuthAccessTokenQuery {
	if oatq == nil {
		return nil
	}
	return &OAuthAccessTokenQuery{
		config:      oatq.config,
		ctx:         oatq.ctx.Clone(),
		order:       append([]oauthaccesstoken.OrderOption{}, oatq.order...),
		inters:      append([]Interceptor{}, oatq.inters...),
		predicates:  append([]predicate.OAuthAccessToken{}, oatq.predicates...),
		withSession: oatq.withSession.Clone(),
		// clone intermediate query.
		sql:  oatq.sql.Clone(),
		path: oatq.path,
	}
}

// WithSession tells the query-builder to eager-load the nodes that are connected to
// the "session" edge. The optional arguments are used to configure the query builder of the edge.
func (oatq *OAuthAccessTokenQuery) WithSession(opts ...func(*OAuthSessionQuery)) *OAuthAccessTokenQuery {
	query := (&OAuthSessionClient{config: oatq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	oatq.withSession = query
	return oatq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Signature string `json:"signature,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OAuthAccessToken.Query().
//		GroupBy(oauthaccesstoken.FieldSignature).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (oatq *OAuthAccessTokenQuery) GroupBy(field string, fields ...string) *OAuthAccessTokenGroupBy {
	oatq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OAuthAccessTokenGroupBy{build: oatq}
	grbuild.flds = &oatq.ctx.Fields
	grbuild.label = oauthaccesstoken.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Signature string `json:"signature,omitempty"`
//	}
//
//	client.OAuthAccessToken.Query().
//		Select(oauthaccesstoken.FieldSignature).
//		Scan(ctx, &v)
func (oatq *OAuthAccessTokenQuery) Select(fields ...string) *OAuthAccessTokenSelect {
	oatq.ctx.Fields = append(oatq.ctx.Fields, fields...)
	sbuild := &OAuthAccessTokenSelect{OAuthAccessTokenQuery: oatq}
	sbuild.label = oauthaccesstoken.Label
	sbuild.flds, sbuild.scan = &oatq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OAuthAccessTokenSelect configured with the given aggregations.
func (oatq *OAuthAccessTokenQuery) Aggregate(fns ...AggregateFunc) *OAuthAccessTokenSelect {
	return oatq.Select().Aggregate(fns...)
}

func (oatq *OAuthAccessTokenQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range oatq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, oatq); err != nil {
				return err
			}
		}
	}
	for _, f := range oatq.ctx.Fields {
		if !oauthaccesstoken.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if oatq.path != nil {
		prev, err := oatq.path(ctx)
		if err != nil {
			return err
		}
		oatq.sql = prev
	}
	return nil
}

func (oatq *OAuthAccessTokenQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OAuthAccessToken, error) {
	var (
		nodes       = []*OAuthAccessToken{}
		withFKs     = oatq.withFKs
		_spec       = oatq.querySpec()
		loadedTypes = [1]bool{
			oatq.withSession != nil,
		}
	)
	if oatq.withSession != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, oauthaccesstoken.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OAuthAccessToken).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OAuthAccessToken{config: oatq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(oatq.modifiers) > 0 {
		_spec.Modifiers = oatq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, oatq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := oatq.withSession; query != nil {
		if err := oatq.loadSession(ctx, query, nodes, nil,
			func(n *OAuthAccessToken, e *OAuthSession) { n.Edges.Session = e }); err != nil {
			return nil, err
		}
	}
	for i := range oatq.loadTotal {
		if err := oatq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (oatq *OAuthAccessTokenQuery) loadSession(ctx context.Context, query *OAuthSessionQuery, nodes []*OAuthAccessToken, init func(*OAuthAccessToken), assign func(*OAuthAccessToken, *OAuthSession)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*OAuthAccessToken)
	for i := range nodes {
		if nodes[i].oauth_access_token_session == nil {
			continue
		}
		fk := *nodes[i].oauth_access_token_session
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(oauthsession.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "oauth_access_token_session" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (oatq *OAuthAccessTokenQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := oatq.querySpec()
	if len(oatq.modifiers) > 0 {
		_spec.Modifiers = oatq.modifiers
	}
	_spec.Node.Columns = oatq.ctx.Fields
	if len(oatq.ctx.Fields) > 0 {
		_spec.Unique = oatq.ctx.Unique != nil && *oatq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, oatq.driver, _spec)
}

func (oatq *OAuthAccessTokenQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(oauthaccesstoken.Table, oauthaccesstoken.Columns, sqlgraph.NewFieldSpec(oauthaccesstoken.FieldID, field.TypeInt))
	_spec.From = oatq.sql
	if unique := oatq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if oatq.path != nil {
		_spec.Unique = true
	}
	if fields := oatq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthaccesstoken.FieldID)
		for i := range fields {
			if fields[i] != oauthaccesstoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := oatq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := oatq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := oatq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := oatq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (oatq *OAuthAccessTokenQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(oatq.driver.Dialect())
	t1 := builder.Table(oauthaccesstoken.Table)
	columns := oatq.ctx.Fields
	if len(columns) == 0 {
		columns = oauthaccesstoken.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if oatq.sql != nil {
		selector = oatq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if oatq.ctx.Unique != nil && *oatq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range oatq.predicates {
		p(selector)
	}
	for _, p := range oatq.order {
		p(selector)
	}
	if offset := oatq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := oatq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OAuthAccessTokenGroupBy is the group-by builder for OAuthAccessToken entities.
type OAuthAccessTokenGroupBy struct {
	selector
	build *OAuthAccessTokenQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (oatgb *OAuthAccessTokenGroupBy) Aggregate(fns ...AggregateFunc) *OAuthAccessTokenGroupBy {
	oatgb.fns = append(oatgb.fns, fns...)
	return oatgb
}

// Scan applies the selector query and scans the result into the given value.
func (oatgb *OAuthAccessTokenGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, oatgb.build.ctx, "GroupBy")
	if err := oatgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OAuthAccessTokenQuery, *OAuthAccessTokenGroupBy](ctx, oatgb.build, oatgb, oatgb.build.inters, v)
}

func (oatgb *OAuthAccessTokenGroupBy) sqlScan(ctx context.Context, root *OAuthAccessTokenQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(oatgb.fns))
	for _, fn := range oatgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*oatgb.flds)+len(oatgb.fns))
		for _, f := range *oatgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*oatgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := oatgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OAuthAccessTokenSelect is the builder for selecting fields of OAuthAccessToken entities.
type OAuthAccessTokenSelect struct {
	*OAuthAccessTokenQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (oats *OAuthAccessTokenSelect) Aggregate(fns ...AggregateFunc) *OAuthAccessTokenSelect {
	oats.fns = append(oats.fns, fns...)
	return oats
}

// Scan applies the selector query and scans the result into the given value.
func (oats *OAuthAccessTokenSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, oats.ctx, "Select")
	if err := oats.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OAuthAccessTokenQuery, *OAuthAccessTokenSelect](ctx, oats.OAuthAccessTokenQuery, oats, oats.inters, v)
}

func (oats *OAuthAccessTokenSelect) sqlScan(ctx context.Context, root *OAuthAccessTokenQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(oats.fns))
	for _, fn := range oats.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*oats.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := oats.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
