// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/koalatea/authserver/server/ent/oauthsession"
)

// OAuthSessionCreate is the builder for creating a OAuthSession entity.
type OAuthSessionCreate struct {
	config
	mutation *OAuthSessionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetIssuer sets the "issuer" field.
func (osc *OAuthSessionCreate) SetIssuer(s string) *OAuthSessionCreate {
	osc.mutation.SetIssuer(s)
	return osc
}

// SetSubject sets the "subject" field.
func (osc *OAuthSessionCreate) SetSubject(s string) *OAuthSessionCreate {
	osc.mutation.SetSubject(s)
	return osc
}

// SetAudiences sets the "audiences" field.
func (osc *OAuthSessionCreate) SetAudiences(s []string) *OAuthSessionCreate {
	osc.mutation.SetAudiences(s)
	return osc
}

// SetExpiresAt sets the "expires_at" field.
func (osc *OAuthSessionCreate) SetExpiresAt(t time.Time) *OAuthSessionCreate {
	osc.mutation.SetExpiresAt(t)
	return osc
}

// SetIssuedAt sets the "issued_at" field.
func (osc *OAuthSessionCreate) SetIssuedAt(t time.Time) *OAuthSessionCreate {
	osc.mutation.SetIssuedAt(t)
	return osc
}

// SetRequestedAt sets the "requested_at" field.
func (osc *OAuthSessionCreate) SetRequestedAt(t time.Time) *OAuthSessionCreate {
	osc.mutation.SetRequestedAt(t)
	return osc
}

// SetAuthTime sets the "auth_time" field.
func (osc *OAuthSessionCreate) SetAuthTime(t time.Time) *OAuthSessionCreate {
	osc.mutation.SetAuthTime(t)
	return osc
}

// SetRequestedScopes sets the "requested_scopes" field.
func (osc *OAuthSessionCreate) SetRequestedScopes(s []string) *OAuthSessionCreate {
	osc.mutation.SetRequestedScopes(s)
	return osc
}

// SetGrantedScopes sets the "granted_scopes" field.
func (osc *OAuthSessionCreate) SetGrantedScopes(s []string) *OAuthSessionCreate {
	osc.mutation.SetGrantedScopes(s)
	return osc
}

// SetRequestedAudiences sets the "requested_audiences" field.
func (osc *OAuthSessionCreate) SetRequestedAudiences(s []string) *OAuthSessionCreate {
	osc.mutation.SetRequestedAudiences(s)
	return osc
}

// SetGrantedAudiences sets the "granted_audiences" field.
func (osc *OAuthSessionCreate) SetGrantedAudiences(s []string) *OAuthSessionCreate {
	osc.mutation.SetGrantedAudiences(s)
	return osc
}

// SetRequest sets the "request" field.
func (osc *OAuthSessionCreate) SetRequest(s string) *OAuthSessionCreate {
	osc.mutation.SetRequest(s)
	return osc
}

// SetForm sets the "form" field.
func (osc *OAuthSessionCreate) SetForm(s string) *OAuthSessionCreate {
	osc.mutation.SetForm(s)
	return osc
}

// Mutation returns the OAuthSessionMutation object of the builder.
func (osc *OAuthSessionCreate) Mutation() *OAuthSessionMutation {
	return osc.mutation
}

// Save creates the OAuthSession in the database.
func (osc *OAuthSessionCreate) Save(ctx context.Context) (*OAuthSession, error) {
	return withHooks(ctx, osc.sqlSave, osc.mutation, osc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (osc *OAuthSessionCreate) SaveX(ctx context.Context) *OAuthSession {
	v, err := osc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (osc *OAuthSessionCreate) Exec(ctx context.Context) error {
	_, err := osc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (osc *OAuthSessionCreate) ExecX(ctx context.Context) {
	if err := osc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (osc *OAuthSessionCreate) check() error {
	if _, ok := osc.mutation.Issuer(); !ok {
		return &ValidationError{Name: "issuer", err: errors.New(`ent: missing required field "OAuthSession.issuer"`)}
	}
	if _, ok := osc.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "OAuthSession.subject"`)}
	}
	if _, ok := osc.mutation.Audiences(); !ok {
		return &ValidationError{Name: "audiences", err: errors.New(`ent: missing required field "OAuthSession.audiences"`)}
	}
	if _, ok := osc.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "OAuthSession.expires_at"`)}
	}
	if _, ok := osc.mutation.IssuedAt(); !ok {
		return &ValidationError{Name: "issued_at", err: errors.New(`ent: missing required field "OAuthSession.issued_at"`)}
	}
	if _, ok := osc.mutation.RequestedAt(); !ok {
		return &ValidationError{Name: "requested_at", err: errors.New(`ent: missing required field "OAuthSession.requested_at"`)}
	}
	if _, ok := osc.mutation.AuthTime(); !ok {
		return &ValidationError{Name: "auth_time", err: errors.New(`ent: missing required field "OAuthSession.auth_time"`)}
	}
	if _, ok := osc.mutation.RequestedScopes(); !ok {
		return &ValidationError{Name: "requested_scopes", err: errors.New(`ent: missing required field "OAuthSession.requested_scopes"`)}
	}
	if _, ok := osc.mutation.GrantedScopes(); !ok {
		return &ValidationError{Name: "granted_scopes", err: errors.New(`ent: missing required field "OAuthSession.granted_scopes"`)}
	}
	if _, ok := osc.mutation.RequestedAudiences(); !ok {
		return &ValidationError{Name: "requested_audiences", err: errors.New(`ent: missing required field "OAuthSession.requested_audiences"`)}
	}
	if _, ok := osc.mutation.GrantedAudiences(); !ok {
		return &ValidationError{Name: "granted_audiences", err: errors.New(`ent: missing required field "OAuthSession.granted_audiences"`)}
	}
	if _, ok := osc.mutation.Request(); !ok {
		return &ValidationError{Name: "request", err: errors.New(`ent: missing required field "OAuthSession.request"`)}
	}
	if _, ok := osc.mutation.Form(); !ok {
		return &ValidationError{Name: "form", err: errors.New(`ent: missing required field "OAuthSession.form"`)}
	}
	return nil
}

func (osc *OAuthSessionCreate) sqlSave(ctx context.Context) (*OAuthSession, error) {
	if err := osc.check(); err != nil {
		return nil, err
	}
	_node, _spec := osc.createSpec()
	if err := sqlgraph.CreateNode(ctx, osc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	osc.mutation.id = &_node.ID
	osc.mutation.done = true
	return _node, nil
}

func (osc *OAuthSessionCreate) createSpec() (*OAuthSession, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthSession{config: osc.config}
		_spec = sqlgraph.NewCreateSpec(oauthsession.Table, sqlgraph.NewFieldSpec(oauthsession.FieldID, field.TypeInt))
	)
	_spec.OnConflict = osc.conflict
	if value, ok := osc.mutation.Issuer(); ok {
		_spec.SetField(oauthsession.FieldIssuer, field.TypeString, value)
		_node.Issuer = value
	}
	if value, ok := osc.mutation.Subject(); ok {
		_spec.SetField(oauthsession.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := osc.mutation.Audiences(); ok {
		_spec.SetField(oauthsession.FieldAudiences, field.TypeJSON, value)
		_node.Audiences = value
	}
	if value, ok := osc.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthsession.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := osc.mutation.IssuedAt(); ok {
		_spec.SetField(oauthsession.FieldIssuedAt, field.TypeTime, value)
		_node.IssuedAt = value
	}
	if value, ok := osc.mutation.RequestedAt(); ok {
		_spec.SetField(oauthsession.FieldRequestedAt, field.TypeTime, value)
		_node.RequestedAt = value
	}
	if value, ok := osc.mutation.AuthTime(); ok {
		_spec.SetField(oauthsession.FieldAuthTime, field.TypeTime, value)
		_node.AuthTime = value
	}
	if value, ok := osc.mutation.RequestedScopes(); ok {
		_spec.SetField(oauthsession.FieldRequestedScopes, field.TypeJSON, value)
		_node.RequestedScopes = value
	}
	if value, ok := osc.mutation.GrantedScopes(); ok {
		_spec.SetField(oauthsession.FieldGrantedScopes, field.TypeJSON, value)
		_node.GrantedScopes = value
	}
	if value, ok := osc.mutation.RequestedAudiences(); ok {
		_spec.SetField(oauthsession.FieldRequestedAudiences, field.TypeJSON, value)
		_node.RequestedAudiences = value
	}
	if value, ok := osc.mutation.GrantedAudiences(); ok {
		_spec.SetField(oauthsession.FieldGrantedAudiences, field.TypeJSON, value)
		_node.GrantedAudiences = value
	}
	if value, ok := osc.mutation.Request(); ok {
		_spec.SetField(oauthsession.FieldRequest, field.TypeString, value)
		_node.Request = value
	}
	if value, ok := osc.mutation.Form(); ok {
		_spec.SetField(oauthsession.FieldForm, field.TypeString, value)
		_node.Form = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthSession.Create().
//		SetIssuer(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthSessionUpsert) {
//			SetIssuer(v+v).
//		}).
//		Exec(ctx)
func (osc *OAuthSessionCreate) OnConflict(opts ...sql.ConflictOption) *OAuthSessionUpsertOne {
	osc.conflict = opts
	return &OAuthSessionUpsertOne{
		create: osc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (osc *OAuthSessionCreate) OnConflictColumns(columns ...string) *OAuthSessionUpsertOne {
	osc.conflict = append(osc.conflict, sql.ConflictColumns(columns...))
	return &OAuthSessionUpsertOne{
		create: osc,
	}
}

type (
	// OAuthSessionUpsertOne is the builder for "upsert"-ing
	//  one OAuthSession node.
	OAuthSessionUpsertOne struct {
		create *OAuthSessionCreate
	}

	// OAuthSessionUpsert is the "OnConflict" setter.
	OAuthSessionUpsert struct {
		*sql.UpdateSet
	}
)

// SetIssuer sets the "issuer" field.
func (u *OAuthSessionUpsert) SetIssuer(v string) *OAuthSessionUpsert {
	u.Set(oauthsession.FieldIssuer, v)
	return u
}

// UpdateIssuer sets the "issuer" field to the value that was provided on create.
func (u *OAuthSessionUpsert) UpdateIssuer() *OAuthSessionUpsert {
	u.SetExcluded(oauthsession.FieldIssuer)
	return u
}

// SetSubject sets the "subject" field.
func (u *OAuthSessionUpsert) SetSubject(v string) *OAuthSessionUpsert {
	u.Set(oauthsession.FieldSubject, v)
	return u
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *OAuthSessionUpsert) UpdateSubject() *OAuthSessionUpsert {
	u.SetExcluded(oauthsession.FieldSubject)
	return u
}

// SetAudiences sets the "audiences" field.
func (u *OAuthSessionUpsert) SetAudiences(v []string) *OAuthSessionUpsert {
	u.Set(oauthsession.FieldAudiences, v)
	return u
}

// UpdateAudiences sets the "audiences" field to the value that was provided on create.
func (u *OAuthSessionUpsert) UpdateAudiences() *OAuthSessionUpsert {
	u.SetExcluded(oauthsession.FieldAudiences)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *OAuthSessionUpsert) SetExpiresAt(v time.Time) *OAuthSessionUpsert {
	u.Set(oauthsession.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OAuthSessionUpsert) UpdateExpiresAt() *OAuthSessionUpsert {
	u.SetExcluded(oauthsession.FieldExpiresAt)
	return u
}

// SetIssuedAt sets the "issued_at" field.
func (u *OAuthSessionUpsert) SetIssuedAt(v time.Time) *OAuthSessionUpsert {
	u.Set(oauthsession.FieldIssuedAt, v)
	return u
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *OAuthSessionUpsert) UpdateIssuedAt() *OAuthSessionUpsert {
	u.SetExcluded(oauthsession.FieldIssuedAt)
	return u
}

// SetRequestedAt sets the "requested_at" field.
func (u *OAuthSessionUpsert) SetRequestedAt(v time.Time) *OAuthSessionUpsert {
	u.Set(oauthsession.FieldRequestedAt, v)
	return u
}

// UpdateRequestedAt sets the "requested_at" field to the value that was provided on create.
func (u *OAuthSessionUpsert) UpdateRequestedAt() *OAuthSessionUpsert {
	u.SetExcluded(oauthsession.FieldRequestedAt)
	return u
}

// SetAuthTime sets the "auth_time" field.
func (u *OAuthSessionUpsert) SetAuthTime(v time.Time) *OAuthSessionUpsert {
	u.Set(oauthsession.FieldAuthTime, v)
	return u
}

// UpdateAuthTime sets the "auth_time" field to the value that was provided on create.
func (u *OAuthSessionUpsert) UpdateAuthTime() *OAuthSessionUpsert {
	u.SetExcluded(oauthsession.FieldAuthTime)
	return u
}

// SetRequestedScopes sets the "requested_scopes" field.
func (u *OAuthSessionUpsert) SetRequestedScopes(v []string) *OAuthSessionUpsert {
	u.Set(oauthsession.FieldRequestedScopes, v)
	return u
}

// UpdateRequestedScopes sets the "requested_scopes" field to the value that was provided on create.
func (u *OAuthSessionUpsert) UpdateRequestedScopes() *OAuthSessionUpsert {
	u.SetExcluded(oauthsession.FieldRequestedScopes)
	return u
}

// SetGrantedScopes sets the "granted_scopes" field.
func (u *OAuthSessionUpsert) SetGrantedScopes(v []string) *OAuthSessionUpsert {
	u.Set(oauthsession.FieldGrantedScopes, v)
	return u
}

// UpdateGrantedScopes sets the "granted_scopes" field to the value that was provided on create.
func (u *OAuthSessionUpsert) UpdateGrantedScopes() *OAuthSessionUpsert {
	u.SetExcluded(oauthsession.FieldGrantedScopes)
	return u
}

// SetRequestedAudiences sets the "requested_audiences" field.
func (u *OAuthSessionUpsert) SetRequestedAudiences(v []string) *OAuthSessionUpsert {
	u.Set(oauthsession.FieldRequestedAudiences, v)
	return u
}

// UpdateRequestedAudiences sets the "requested_audiences" field to the value that was provided on create.
func (u *OAuthSessionUpsert) UpdateRequestedAudiences() *OAuthSessionUpsert {
	u.SetExcluded(oauthsession.FieldRequestedAudiences)
	return u
}

// SetGrantedAudiences sets the "granted_audiences" field.
func (u *OAuthSessionUpsert) SetGrantedAudiences(v []string) *OAuthSessionUpsert {
	u.Set(oauthsession.FieldGrantedAudiences, v)
	return u
}

// UpdateGrantedAudiences sets the "granted_audiences" field to the value that was provided on create.
func (u *OAuthSessionUpsert) UpdateGrantedAudiences() *OAuthSessionUpsert {
	u.SetExcluded(oauthsession.FieldGrantedAudiences)
	return u
}

// SetRequest sets the "request" field.
func (u *OAuthSessionUpsert) SetRequest(v string) *OAuthSessionUpsert {
	u.Set(oauthsession.FieldRequest, v)
	return u
}

// UpdateRequest sets the "request" field to the value that was provided on create.
func (u *OAuthSessionUpsert) UpdateRequest() *OAuthSessionUpsert {
	u.SetExcluded(oauthsession.FieldRequest)
	return u
}

// SetForm sets the "form" field.
func (u *OAuthSessionUpsert) SetForm(v string) *OAuthSessionUpsert {
	u.Set(oauthsession.FieldForm, v)
	return u
}

// UpdateForm sets the "form" field to the value that was provided on create.
func (u *OAuthSessionUpsert) UpdateForm() *OAuthSessionUpsert {
	u.SetExcluded(oauthsession.FieldForm)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OAuthSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthSessionUpsertOne) UpdateNewValues() *OAuthSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthSession.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OAuthSessionUpsertOne) Ignore() *OAuthSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthSessionUpsertOne) DoNothing() *OAuthSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthSessionCreate.OnConflict
// documentation for more info.
func (u *OAuthSessionUpsertOne) Update(set func(*OAuthSessionUpsert)) *OAuthSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetIssuer sets the "issuer" field.
func (u *OAuthSessionUpsertOne) SetIssuer(v string) *OAuthSessionUpsertOne {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.SetIssuer(v)
	})
}

// UpdateIssuer sets the "issuer" field to the value that was provided on create.
func (u *OAuthSessionUpsertOne) UpdateIssuer() *OAuthSessionUpsertOne {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.UpdateIssuer()
	})
}

// SetSubject sets the "subject" field.
func (u *OAuthSessionUpsertOne) SetSubject(v string) *OAuthSessionUpsertOne {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *OAuthSessionUpsertOne) UpdateSubject() *OAuthSessionUpsertOne {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.UpdateSubject()
	})
}

// SetAudiences sets the "audiences" field.
func (u *OAuthSessionUpsertOne) SetAudiences(v []string) *OAuthSessionUpsertOne {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.SetAudiences(v)
	})
}

// UpdateAudiences sets the "audiences" field to the value that was provided on create.
func (u *OAuthSessionUpsertOne) UpdateAudiences() *OAuthSessionUpsertOne {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.UpdateAudiences()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *OAuthSessionUpsertOne) SetExpiresAt(v time.Time) *OAuthSessionUpsertOne {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OAuthSessionUpsertOne) UpdateExpiresAt() *OAuthSessionUpsertOne {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetIssuedAt sets the "issued_at" field.
func (u *OAuthSessionUpsertOne) SetIssuedAt(v time.Time) *OAuthSessionUpsertOne {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.SetIssuedAt(v)
	})
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *OAuthSessionUpsertOne) UpdateIssuedAt() *OAuthSessionUpsertOne {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.UpdateIssuedAt()
	})
}

// SetRequestedAt sets the "requested_at" field.
func (u *OAuthSessionUpsertOne) SetRequestedAt(v time.Time) *OAuthSessionUpsertOne {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.SetRequestedAt(v)
	})
}

// UpdateRequestedAt sets the "requested_at" field to the value that was provided on create.
func (u *OAuthSessionUpsertOne) UpdateRequestedAt() *OAuthSessionUpsertOne {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.UpdateRequestedAt()
	})
}

// SetAuthTime sets the "auth_time" field.
func (u *OAuthSessionUpsertOne) SetAuthTime(v time.Time) *OAuthSessionUpsertOne {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.SetAuthTime(v)
	})
}

// UpdateAuthTime sets the "auth_time" field to the value that was provided on create.
func (u *OAuthSessionUpsertOne) UpdateAuthTime() *OAuthSessionUpsertOne {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.UpdateAuthTime()
	})
}

// SetRequestedScopes sets the "requested_scopes" field.
func (u *OAuthSessionUpsertOne) SetRequestedScopes(v []string) *OAuthSessionUpsertOne {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.SetRequestedScopes(v)
	})
}

// UpdateRequestedScopes sets the "requested_scopes" field to the value that was provided on create.
func (u *OAuthSessionUpsertOne) UpdateRequestedScopes() *OAuthSessionUpsertOne {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.UpdateRequestedScopes()
	})
}

// SetGrantedScopes sets the "granted_scopes" field.
func (u *OAuthSessionUpsertOne) SetGrantedScopes(v []string) *OAuthSessionUpsertOne {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.SetGrantedScopes(v)
	})
}

// UpdateGrantedScopes sets the "granted_scopes" field to the value that was provided on create.
func (u *OAuthSessionUpsertOne) UpdateGrantedScopes() *OAuthSessionUpsertOne {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.UpdateGrantedScopes()
	})
}

// SetRequestedAudiences sets the "requested_audiences" field.
func (u *OAuthSessionUpsertOne) SetRequestedAudiences(v []string) *OAuthSessionUpsertOne {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.SetRequestedAudiences(v)
	})
}

// UpdateRequestedAudiences sets the "requested_audiences" field to the value that was provided on create.
func (u *OAuthSessionUpsertOne) UpdateRequestedAudiences() *OAuthSessionUpsertOne {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.UpdateRequestedAudiences()
	})
}

// SetGrantedAudiences sets the "granted_audiences" field.
func (u *OAuthSessionUpsertOne) SetGrantedAudiences(v []string) *OAuthSessionUpsertOne {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.SetGrantedAudiences(v)
	})
}

// UpdateGrantedAudiences sets the "granted_audiences" field to the value that was provided on create.
func (u *OAuthSessionUpsertOne) UpdateGrantedAudiences() *OAuthSessionUpsertOne {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.UpdateGrantedAudiences()
	})
}

// SetRequest sets the "request" field.
func (u *OAuthSessionUpsertOne) SetRequest(v string) *OAuthSessionUpsertOne {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.SetRequest(v)
	})
}

// UpdateRequest sets the "request" field to the value that was provided on create.
func (u *OAuthSessionUpsertOne) UpdateRequest() *OAuthSessionUpsertOne {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.UpdateRequest()
	})
}

// SetForm sets the "form" field.
func (u *OAuthSessionUpsertOne) SetForm(v string) *OAuthSessionUpsertOne {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.SetForm(v)
	})
}

// UpdateForm sets the "form" field to the value that was provided on create.
func (u *OAuthSessionUpsertOne) UpdateForm() *OAuthSessionUpsertOne {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.UpdateForm()
	})
}

// Exec executes the query.
func (u *OAuthSessionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthSessionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthSessionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OAuthSessionUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OAuthSessionUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OAuthSessionCreateBulk is the builder for creating many OAuthSession entities in bulk.
type OAuthSessionCreateBulk struct {
	config
	err      error
	builders []*OAuthSessionCreate
	conflict []sql.ConflictOption
}

// Save creates the OAuthSession entities in the database.
func (oscb *OAuthSessionCreateBulk) Save(ctx context.Context) ([]*OAuthSession, error) {
	if oscb.err != nil {
		return nil, oscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(oscb.builders))
	nodes := make([]*OAuthSession, len(oscb.builders))
	mutators := make([]Mutator, len(oscb.builders))
	for i := range oscb.builders {
		func(i int, root context.Context) {
			builder := oscb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, oscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = oscb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, oscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, oscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (oscb *OAuthSessionCreateBulk) SaveX(ctx context.Context) []*OAuthSession {
	v, err := oscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (oscb *OAuthSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := oscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oscb *OAuthSessionCreateBulk) ExecX(ctx context.Context) {
	if err := oscb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthSession.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthSessionUpsert) {
//			SetIssuer(v+v).
//		}).
//		Exec(ctx)
func (oscb *OAuthSessionCreateBulk) OnConflict(opts ...sql.ConflictOption) *OAuthSessionUpsertBulk {
	oscb.conflict = opts
	return &OAuthSessionUpsertBulk{
		create: oscb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (oscb *OAuthSessionCreateBulk) OnConflictColumns(columns ...string) *OAuthSessionUpsertBulk {
	oscb.conflict = append(oscb.conflict, sql.ConflictColumns(columns...))
	return &OAuthSessionUpsertBulk{
		create: oscb,
	}
}

// OAuthSessionUpsertBulk is the builder for "upsert"-ing
// a bulk of OAuthSession nodes.
type OAuthSessionUpsertBulk struct {
	create *OAuthSessionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OAuthSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthSessionUpsertBulk) UpdateNewValues() *OAuthSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthSession.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OAuthSessionUpsertBulk) Ignore() *OAuthSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthSessionUpsertBulk) DoNothing() *OAuthSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthSessionCreateBulk.OnConflict
// documentation for more info.
func (u *OAuthSessionUpsertBulk) Update(set func(*OAuthSessionUpsert)) *OAuthSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetIssuer sets the "issuer" field.
func (u *OAuthSessionUpsertBulk) SetIssuer(v string) *OAuthSessionUpsertBulk {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.SetIssuer(v)
	})
}

// UpdateIssuer sets the "issuer" field to the value that was provided on create.
func (u *OAuthSessionUpsertBulk) UpdateIssuer() *OAuthSessionUpsertBulk {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.UpdateIssuer()
	})
}

// SetSubject sets the "subject" field.
func (u *OAuthSessionUpsertBulk) SetSubject(v string) *OAuthSessionUpsertBulk {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *OAuthSessionUpsertBulk) UpdateSubject() *OAuthSessionUpsertBulk {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.UpdateSubject()
	})
}

// SetAudiences sets the "audiences" field.
func (u *OAuthSessionUpsertBulk) SetAudiences(v []string) *OAuthSessionUpsertBulk {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.SetAudiences(v)
	})
}

// UpdateAudiences sets the "audiences" field to the value that was provided on create.
func (u *OAuthSessionUpsertBulk) UpdateAudiences() *OAuthSessionUpsertBulk {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.UpdateAudiences()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *OAuthSessionUpsertBulk) SetExpiresAt(v time.Time) *OAuthSessionUpsertBulk {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *OAuthSessionUpsertBulk) UpdateExpiresAt() *OAuthSessionUpsertBulk {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetIssuedAt sets the "issued_at" field.
func (u *OAuthSessionUpsertBulk) SetIssuedAt(v time.Time) *OAuthSessionUpsertBulk {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.SetIssuedAt(v)
	})
}

// UpdateIssuedAt sets the "issued_at" field to the value that was provided on create.
func (u *OAuthSessionUpsertBulk) UpdateIssuedAt() *OAuthSessionUpsertBulk {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.UpdateIssuedAt()
	})
}

// SetRequestedAt sets the "requested_at" field.
func (u *OAuthSessionUpsertBulk) SetRequestedAt(v time.Time) *OAuthSessionUpsertBulk {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.SetRequestedAt(v)
	})
}

// UpdateRequestedAt sets the "requested_at" field to the value that was provided on create.
func (u *OAuthSessionUpsertBulk) UpdateRequestedAt() *OAuthSessionUpsertBulk {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.UpdateRequestedAt()
	})
}

// SetAuthTime sets the "auth_time" field.
func (u *OAuthSessionUpsertBulk) SetAuthTime(v time.Time) *OAuthSessionUpsertBulk {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.SetAuthTime(v)
	})
}

// UpdateAuthTime sets the "auth_time" field to the value that was provided on create.
func (u *OAuthSessionUpsertBulk) UpdateAuthTime() *OAuthSessionUpsertBulk {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.UpdateAuthTime()
	})
}

// SetRequestedScopes sets the "requested_scopes" field.
func (u *OAuthSessionUpsertBulk) SetRequestedScopes(v []string) *OAuthSessionUpsertBulk {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.SetRequestedScopes(v)
	})
}

// UpdateRequestedScopes sets the "requested_scopes" field to the value that was provided on create.
func (u *OAuthSessionUpsertBulk) UpdateRequestedScopes() *OAuthSessionUpsertBulk {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.UpdateRequestedScopes()
	})
}

// SetGrantedScopes sets the "granted_scopes" field.
func (u *OAuthSessionUpsertBulk) SetGrantedScopes(v []string) *OAuthSessionUpsertBulk {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.SetGrantedScopes(v)
	})
}

// UpdateGrantedScopes sets the "granted_scopes" field to the value that was provided on create.
func (u *OAuthSessionUpsertBulk) UpdateGrantedScopes() *OAuthSessionUpsertBulk {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.UpdateGrantedScopes()
	})
}

// SetRequestedAudiences sets the "requested_audiences" field.
func (u *OAuthSessionUpsertBulk) SetRequestedAudiences(v []string) *OAuthSessionUpsertBulk {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.SetRequestedAudiences(v)
	})
}

// UpdateRequestedAudiences sets the "requested_audiences" field to the value that was provided on create.
func (u *OAuthSessionUpsertBulk) UpdateRequestedAudiences() *OAuthSessionUpsertBulk {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.UpdateRequestedAudiences()
	})
}

// SetGrantedAudiences sets the "granted_audiences" field.
func (u *OAuthSessionUpsertBulk) SetGrantedAudiences(v []string) *OAuthSessionUpsertBulk {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.SetGrantedAudiences(v)
	})
}

// UpdateGrantedAudiences sets the "granted_audiences" field to the value that was provided on create.
func (u *OAuthSessionUpsertBulk) UpdateGrantedAudiences() *OAuthSessionUpsertBulk {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.UpdateGrantedAudiences()
	})
}

// SetRequest sets the "request" field.
func (u *OAuthSessionUpsertBulk) SetRequest(v string) *OAuthSessionUpsertBulk {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.SetRequest(v)
	})
}

// UpdateRequest sets the "request" field to the value that was provided on create.
func (u *OAuthSessionUpsertBulk) UpdateRequest() *OAuthSessionUpsertBulk {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.UpdateRequest()
	})
}

// SetForm sets the "form" field.
func (u *OAuthSessionUpsertBulk) SetForm(v string) *OAuthSessionUpsertBulk {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.SetForm(v)
	})
}

// UpdateForm sets the "form" field to the value that was provided on create.
func (u *OAuthSessionUpsertBulk) UpdateForm() *OAuthSessionUpsertBulk {
	return u.Update(func(s *OAuthSessionUpsert) {
		s.UpdateForm()
	})
}

// Exec executes the query.
func (u *OAuthSessionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OAuthSessionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthSessionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthSessionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
