// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/koalatea/authserver/server/ent/oauthrefreshtoken"
	"github.com/koalatea/authserver/server/ent/predicate"
)

// OAuthRefreshTokenDelete is the builder for deleting a OAuthRefreshToken entity.
type OAuthRefreshTokenDelete struct {
	config
	hooks    []Hook
	mutation *OAuthRefreshTokenMutation
}

// Where appends a list predicates to the OAuthRefreshTokenDelete builder.
func (ortd *OAuthRefreshTokenDelete) Where(ps ...predicate.OAuthRefreshToken) *OAuthRefreshTokenDelete {
	ortd.mutation.Where(ps...)
	return ortd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ortd *OAuthRefreshTokenDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ortd.hooks) == 0 {
		affected, err = ortd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*OAuthRefreshTokenMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ortd.mutation = mutation
			affected, err = ortd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ortd.hooks) - 1; i >= 0; i-- {
			if ortd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ortd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ortd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ortd *OAuthRefreshTokenDelete) ExecX(ctx context.Context) int {
	n, err := ortd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ortd *OAuthRefreshTokenDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: oauthrefreshtoken.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: oauthrefreshtoken.FieldID,
			},
		},
	}
	if ps := ortd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ortd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// OAuthRefreshTokenDeleteOne is the builder for deleting a single OAuthRefreshToken entity.
type OAuthRefreshTokenDeleteOne struct {
	ortd *OAuthRefreshTokenDelete
}

// Exec executes the deletion query.
func (ortdo *OAuthRefreshTokenDeleteOne) Exec(ctx context.Context) error {
	n, err := ortdo.ortd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{oauthrefreshtoken.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ortdo *OAuthRefreshTokenDeleteOne) ExecX(ctx context.Context) {
	ortdo.ortd.ExecX(ctx)
}
