// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/koalatea/authserver/server/ent/oidcsession"
	"github.com/koalatea/authserver/server/ent/predicate"
)

// OIDCSessionQuery is the builder for querying OIDCSession entities.
type OIDCSessionQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.OIDCSession
	modifiers  []func(*sql.Selector)
	loadTotal  []func(context.Context, []*OIDCSession) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OIDCSessionQuery builder.
func (osq *OIDCSessionQuery) Where(ps ...predicate.OIDCSession) *OIDCSessionQuery {
	osq.predicates = append(osq.predicates, ps...)
	return osq
}

// Limit adds a limit step to the query.
func (osq *OIDCSessionQuery) Limit(limit int) *OIDCSessionQuery {
	osq.limit = &limit
	return osq
}

// Offset adds an offset step to the query.
func (osq *OIDCSessionQuery) Offset(offset int) *OIDCSessionQuery {
	osq.offset = &offset
	return osq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (osq *OIDCSessionQuery) Unique(unique bool) *OIDCSessionQuery {
	osq.unique = &unique
	return osq
}

// Order adds an order step to the query.
func (osq *OIDCSessionQuery) Order(o ...OrderFunc) *OIDCSessionQuery {
	osq.order = append(osq.order, o...)
	return osq
}

// First returns the first OIDCSession entity from the query.
// Returns a *NotFoundError when no OIDCSession was found.
func (osq *OIDCSessionQuery) First(ctx context.Context) (*OIDCSession, error) {
	nodes, err := osq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{oidcsession.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (osq *OIDCSessionQuery) FirstX(ctx context.Context) *OIDCSession {
	node, err := osq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OIDCSession ID from the query.
// Returns a *NotFoundError when no OIDCSession ID was found.
func (osq *OIDCSessionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = osq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{oidcsession.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (osq *OIDCSessionQuery) FirstIDX(ctx context.Context) int {
	id, err := osq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OIDCSession entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OIDCSession entity is found.
// Returns a *NotFoundError when no OIDCSession entities are found.
func (osq *OIDCSessionQuery) Only(ctx context.Context) (*OIDCSession, error) {
	nodes, err := osq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{oidcsession.Label}
	default:
		return nil, &NotSingularError{oidcsession.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (osq *OIDCSessionQuery) OnlyX(ctx context.Context) *OIDCSession {
	node, err := osq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OIDCSession ID in the query.
// Returns a *NotSingularError when more than one OIDCSession ID is found.
// Returns a *NotFoundError when no entities are found.
func (osq *OIDCSessionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = osq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{oidcsession.Label}
	default:
		err = &NotSingularError{oidcsession.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (osq *OIDCSessionQuery) OnlyIDX(ctx context.Context) int {
	id, err := osq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OIDCSessions.
func (osq *OIDCSessionQuery) All(ctx context.Context) ([]*OIDCSession, error) {
	if err := osq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return osq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (osq *OIDCSessionQuery) AllX(ctx context.Context) []*OIDCSession {
	nodes, err := osq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OIDCSession IDs.
func (osq *OIDCSessionQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := osq.Select(oidcsession.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (osq *OIDCSessionQuery) IDsX(ctx context.Context) []int {
	ids, err := osq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (osq *OIDCSessionQuery) Count(ctx context.Context) (int, error) {
	if err := osq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return osq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (osq *OIDCSessionQuery) CountX(ctx context.Context) int {
	count, err := osq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (osq *OIDCSessionQuery) Exist(ctx context.Context) (bool, error) {
	if err := osq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return osq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (osq *OIDCSessionQuery) ExistX(ctx context.Context) bool {
	exist, err := osq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OIDCSessionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (osq *OIDCSessionQuery) Clone() *OIDCSessionQuery {
	if osq == nil {
		return nil
	}
	return &OIDCSessionQuery{
		config:     osq.config,
		limit:      osq.limit,
		offset:     osq.offset,
		order:      append([]OrderFunc{}, osq.order...),
		predicates: append([]predicate.OIDCSession{}, osq.predicates...),
		// clone intermediate query.
		sql:    osq.sql.Clone(),
		path:   osq.path,
		unique: osq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Issuer string `json:"issuer,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OIDCSession.Query().
//		GroupBy(oidcsession.FieldIssuer).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (osq *OIDCSessionQuery) GroupBy(field string, fields ...string) *OIDCSessionGroupBy {
	grbuild := &OIDCSessionGroupBy{config: osq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := osq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return osq.sqlQuery(ctx), nil
	}
	grbuild.label = oidcsession.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Issuer string `json:"issuer,omitempty"`
//	}
//
//	client.OIDCSession.Query().
//		Select(oidcsession.FieldIssuer).
//		Scan(ctx, &v)
func (osq *OIDCSessionQuery) Select(fields ...string) *OIDCSessionSelect {
	osq.fields = append(osq.fields, fields...)
	selbuild := &OIDCSessionSelect{OIDCSessionQuery: osq}
	selbuild.label = oidcsession.Label
	selbuild.flds, selbuild.scan = &osq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a OIDCSessionSelect configured with the given aggregations.
func (osq *OIDCSessionQuery) Aggregate(fns ...AggregateFunc) *OIDCSessionSelect {
	return osq.Select().Aggregate(fns...)
}

func (osq *OIDCSessionQuery) prepareQuery(ctx context.Context) error {
	for _, f := range osq.fields {
		if !oidcsession.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if osq.path != nil {
		prev, err := osq.path(ctx)
		if err != nil {
			return err
		}
		osq.sql = prev
	}
	return nil
}

func (osq *OIDCSessionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OIDCSession, error) {
	var (
		nodes = []*OIDCSession{}
		_spec = osq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OIDCSession).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OIDCSession{config: osq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(osq.modifiers) > 0 {
		_spec.Modifiers = osq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, osq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	for i := range osq.loadTotal {
		if err := osq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (osq *OIDCSessionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := osq.querySpec()
	if len(osq.modifiers) > 0 {
		_spec.Modifiers = osq.modifiers
	}
	_spec.Node.Columns = osq.fields
	if len(osq.fields) > 0 {
		_spec.Unique = osq.unique != nil && *osq.unique
	}
	return sqlgraph.CountNodes(ctx, osq.driver, _spec)
}

func (osq *OIDCSessionQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := osq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (osq *OIDCSessionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   oidcsession.Table,
			Columns: oidcsession.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: oidcsession.FieldID,
			},
		},
		From:   osq.sql,
		Unique: true,
	}
	if unique := osq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := osq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oidcsession.FieldID)
		for i := range fields {
			if fields[i] != oidcsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := osq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := osq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := osq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := osq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (osq *OIDCSessionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(osq.driver.Dialect())
	t1 := builder.Table(oidcsession.Table)
	columns := osq.fields
	if len(columns) == 0 {
		columns = oidcsession.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if osq.sql != nil {
		selector = osq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if osq.unique != nil && *osq.unique {
		selector.Distinct()
	}
	for _, p := range osq.predicates {
		p(selector)
	}
	for _, p := range osq.order {
		p(selector)
	}
	if offset := osq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := osq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OIDCSessionGroupBy is the group-by builder for OIDCSession entities.
type OIDCSessionGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (osgb *OIDCSessionGroupBy) Aggregate(fns ...AggregateFunc) *OIDCSessionGroupBy {
	osgb.fns = append(osgb.fns, fns...)
	return osgb
}

// Scan applies the group-by query and scans the result into the given value.
func (osgb *OIDCSessionGroupBy) Scan(ctx context.Context, v any) error {
	query, err := osgb.path(ctx)
	if err != nil {
		return err
	}
	osgb.sql = query
	return osgb.sqlScan(ctx, v)
}

func (osgb *OIDCSessionGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range osgb.fields {
		if !oidcsession.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := osgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := osgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (osgb *OIDCSessionGroupBy) sqlQuery() *sql.Selector {
	selector := osgb.sql.Select()
	aggregation := make([]string, 0, len(osgb.fns))
	for _, fn := range osgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(osgb.fields)+len(osgb.fns))
		for _, f := range osgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(osgb.fields...)...)
}

// OIDCSessionSelect is the builder for selecting fields of OIDCSession entities.
type OIDCSessionSelect struct {
	*OIDCSessionQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (oss *OIDCSessionSelect) Aggregate(fns ...AggregateFunc) *OIDCSessionSelect {
	oss.fns = append(oss.fns, fns...)
	return oss
}

// Scan applies the selector query and scans the result into the given value.
func (oss *OIDCSessionSelect) Scan(ctx context.Context, v any) error {
	if err := oss.prepareQuery(ctx); err != nil {
		return err
	}
	oss.sql = oss.OIDCSessionQuery.sqlQuery(ctx)
	return oss.sqlScan(ctx, v)
}

func (oss *OIDCSessionSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(oss.fns))
	for _, fn := range oss.fns {
		aggregation = append(aggregation, fn(oss.sql))
	}
	switch n := len(*oss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		oss.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		oss.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := oss.sql.Query()
	if err := oss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
