// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/koalatea/authserver/server/ent/oauthsession"
	"github.com/koalatea/authserver/server/ent/pkce"
)

// PKCECreate is the builder for creating a PKCE entity.
type PKCECreate struct {
	config
	mutation *PKCEMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCode sets the "code" field.
func (pc *PKCECreate) SetCode(s string) *PKCECreate {
	pc.mutation.SetCode(s)
	return pc
}

// SetSessionID sets the "session" edge to the OAuthSession entity by ID.
func (pc *PKCECreate) SetSessionID(id int) *PKCECreate {
	pc.mutation.SetSessionID(id)
	return pc
}

// SetNillableSessionID sets the "session" edge to the OAuthSession entity by ID if the given value is not nil.
func (pc *PKCECreate) SetNillableSessionID(id *int) *PKCECreate {
	if id != nil {
		pc = pc.SetSessionID(*id)
	}
	return pc
}

// SetSession sets the "session" edge to the OAuthSession entity.
func (pc *PKCECreate) SetSession(o *OAuthSession) *PKCECreate {
	return pc.SetSessionID(o.ID)
}

// Mutation returns the PKCEMutation object of the builder.
func (pc *PKCECreate) Mutation() *PKCEMutation {
	return pc.mutation
}

// Save creates the PKCE in the database.
func (pc *PKCECreate) Save(ctx context.Context) (*PKCE, error) {
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PKCECreate) SaveX(ctx context.Context) *PKCE {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PKCECreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PKCECreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PKCECreate) check() error {
	if _, ok := pc.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "PKCE.code"`)}
	}
	return nil
}

func (pc *PKCECreate) sqlSave(ctx context.Context) (*PKCE, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *PKCECreate) createSpec() (*PKCE, *sqlgraph.CreateSpec) {
	var (
		_node = &PKCE{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(pkce.Table, sqlgraph.NewFieldSpec(pkce.FieldID, field.TypeInt))
	)
	_spec.OnConflict = pc.conflict
	if value, ok := pc.mutation.Code(); ok {
		_spec.SetField(pkce.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if nodes := pc.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pkce.SessionTable,
			Columns: []string{pkce.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthsession.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.pkce_session = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PKCE.Create().
//		SetCode(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PKCEUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (pc *PKCECreate) OnConflict(opts ...sql.ConflictOption) *PKCEUpsertOne {
	pc.conflict = opts
	return &PKCEUpsertOne{
		create: pc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PKCE.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (pc *PKCECreate) OnConflictColumns(columns ...string) *PKCEUpsertOne {
	pc.conflict = append(pc.conflict, sql.ConflictColumns(columns...))
	return &PKCEUpsertOne{
		create: pc,
	}
}

type (
	// PKCEUpsertOne is the builder for "upsert"-ing
	//  one PKCE node.
	PKCEUpsertOne struct {
		create *PKCECreate
	}

	// PKCEUpsert is the "OnConflict" setter.
	PKCEUpsert struct {
		*sql.UpdateSet
	}
)

// SetCode sets the "code" field.
func (u *PKCEUpsert) SetCode(v string) *PKCEUpsert {
	u.Set(pkce.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *PKCEUpsert) UpdateCode() *PKCEUpsert {
	u.SetExcluded(pkce.FieldCode)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PKCE.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PKCEUpsertOne) UpdateNewValues() *PKCEUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PKCE.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PKCEUpsertOne) Ignore() *PKCEUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PKCEUpsertOne) DoNothing() *PKCEUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PKCECreate.OnConflict
// documentation for more info.
func (u *PKCEUpsertOne) Update(set func(*PKCEUpsert)) *PKCEUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PKCEUpsert{UpdateSet: update})
	}))
	return u
}

// SetCode sets the "code" field.
func (u *PKCEUpsertOne) SetCode(v string) *PKCEUpsertOne {
	return u.Update(func(s *PKCEUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *PKCEUpsertOne) UpdateCode() *PKCEUpsertOne {
	return u.Update(func(s *PKCEUpsert) {
		s.UpdateCode()
	})
}

// Exec executes the query.
func (u *PKCEUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PKCECreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PKCEUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PKCEUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PKCEUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PKCECreateBulk is the builder for creating many PKCE entities in bulk.
type PKCECreateBulk struct {
	config
	err      error
	builders []*PKCECreate
	conflict []sql.ConflictOption
}

// Save creates the PKCE entities in the database.
func (pcb *PKCECreateBulk) Save(ctx context.Context) ([]*PKCE, error) {
	if pcb.err != nil {
		return nil, pcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*PKCE, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PKCEMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = pcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PKCECreateBulk) SaveX(ctx context.Context) []*PKCE {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PKCECreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PKCECreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PKCE.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PKCEUpsert) {
//			SetCode(v+v).
//		}).
//		Exec(ctx)
func (pcb *PKCECreateBulk) OnConflict(opts ...sql.ConflictOption) *PKCEUpsertBulk {
	pcb.conflict = opts
	return &PKCEUpsertBulk{
		create: pcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PKCE.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (pcb *PKCECreateBulk) OnConflictColumns(columns ...string) *PKCEUpsertBulk {
	pcb.conflict = append(pcb.conflict, sql.ConflictColumns(columns...))
	return &PKCEUpsertBulk{
		create: pcb,
	}
}

// PKCEUpsertBulk is the builder for "upsert"-ing
// a bulk of PKCE nodes.
type PKCEUpsertBulk struct {
	create *PKCECreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PKCE.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PKCEUpsertBulk) UpdateNewValues() *PKCEUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PKCE.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PKCEUpsertBulk) Ignore() *PKCEUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PKCEUpsertBulk) DoNothing() *PKCEUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PKCECreateBulk.OnConflict
// documentation for more info.
func (u *PKCEUpsertBulk) Update(set func(*PKCEUpsert)) *PKCEUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PKCEUpsert{UpdateSet: update})
	}))
	return u
}

// SetCode sets the "code" field.
func (u *PKCEUpsertBulk) SetCode(v string) *PKCEUpsertBulk {
	return u.Update(func(s *PKCEUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *PKCEUpsertBulk) UpdateCode() *PKCEUpsertBulk {
	return u.Update(func(s *PKCEUpsert) {
		s.UpdateCode()
	})
}

// Exec executes the query.
func (u *PKCEUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PKCECreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PKCECreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PKCEUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
