// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/koalatea/authserver/server/ent/publicjwkset"
)

// PublicJWKSet is the model entity for the PublicJWKSet schema.
type PublicJWKSet struct {
	config
	// ID of the ent.
	ID           int `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PublicJWKSet) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case publicjwkset.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PublicJWKSet fields.
func (pjs *PublicJWKSet) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case publicjwkset.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pjs.ID = int(value.Int64)
		default:
			pjs.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PublicJWKSet.
// This includes values selected through modifiers, order, etc.
func (pjs *PublicJWKSet) Value(name string) (ent.Value, error) {
	return pjs.selectValues.Get(name)
}

// Update returns a builder for updating this PublicJWKSet.
// Note that you need to call PublicJWKSet.Unwrap() before calling this method if this PublicJWKSet
// was returned from a transaction, and the transaction was committed or rolled back.
func (pjs *PublicJWKSet) Update() *PublicJWKSetUpdateOne {
	return NewPublicJWKSetClient(pjs.config).UpdateOne(pjs)
}

// Unwrap unwraps the PublicJWKSet entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pjs *PublicJWKSet) Unwrap() *PublicJWKSet {
	_tx, ok := pjs.config.driver.(*txDriver)
	if !ok {
		panic("ent: PublicJWKSet is not a transactional entity")
	}
	pjs.config.driver = _tx.drv
	return pjs
}

// String implements the fmt.Stringer.
func (pjs *PublicJWKSet) String() string {
	var builder strings.Builder
	builder.WriteString("PublicJWKSet(")
	builder.WriteString(fmt.Sprintf("id=%v", pjs.ID))
	builder.WriteByte(')')
	return builder.String()
}

// PublicJWKSets is a parsable slice of PublicJWKSet.
type PublicJWKSets []*PublicJWKSet
