// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/koalatea/authserver/server/ent/predicate"
	"github.com/koalatea/authserver/server/ent/publicjwk"
)

// PublicJWKQuery is the builder for querying PublicJWK entities.
type PublicJWKQuery struct {
	config
	ctx        *QueryContext
	order      []publicjwk.OrderOption
	inters     []Interceptor
	predicates []predicate.PublicJWK
	modifiers  []func(*sql.Selector)
	loadTotal  []func(context.Context, []*PublicJWK) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PublicJWKQuery builder.
func (pjq *PublicJWKQuery) Where(ps ...predicate.PublicJWK) *PublicJWKQuery {
	pjq.predicates = append(pjq.predicates, ps...)
	return pjq
}

// Limit the number of records to be returned by this query.
func (pjq *PublicJWKQuery) Limit(limit int) *PublicJWKQuery {
	pjq.ctx.Limit = &limit
	return pjq
}

// Offset to start from.
func (pjq *PublicJWKQuery) Offset(offset int) *PublicJWKQuery {
	pjq.ctx.Offset = &offset
	return pjq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pjq *PublicJWKQuery) Unique(unique bool) *PublicJWKQuery {
	pjq.ctx.Unique = &unique
	return pjq
}

// Order specifies how the records should be ordered.
func (pjq *PublicJWKQuery) Order(o ...publicjwk.OrderOption) *PublicJWKQuery {
	pjq.order = append(pjq.order, o...)
	return pjq
}

// First returns the first PublicJWK entity from the query.
// Returns a *NotFoundError when no PublicJWK was found.
func (pjq *PublicJWKQuery) First(ctx context.Context) (*PublicJWK, error) {
	nodes, err := pjq.Limit(1).All(setContextOp(ctx, pjq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{publicjwk.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pjq *PublicJWKQuery) FirstX(ctx context.Context) *PublicJWK {
	node, err := pjq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PublicJWK ID from the query.
// Returns a *NotFoundError when no PublicJWK ID was found.
func (pjq *PublicJWKQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pjq.Limit(1).IDs(setContextOp(ctx, pjq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{publicjwk.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pjq *PublicJWKQuery) FirstIDX(ctx context.Context) int {
	id, err := pjq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PublicJWK entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PublicJWK entity is found.
// Returns a *NotFoundError when no PublicJWK entities are found.
func (pjq *PublicJWKQuery) Only(ctx context.Context) (*PublicJWK, error) {
	nodes, err := pjq.Limit(2).All(setContextOp(ctx, pjq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{publicjwk.Label}
	default:
		return nil, &NotSingularError{publicjwk.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pjq *PublicJWKQuery) OnlyX(ctx context.Context) *PublicJWK {
	node, err := pjq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PublicJWK ID in the query.
// Returns a *NotSingularError when more than one PublicJWK ID is found.
// Returns a *NotFoundError when no entities are found.
func (pjq *PublicJWKQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pjq.Limit(2).IDs(setContextOp(ctx, pjq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{publicjwk.Label}
	default:
		err = &NotSingularError{publicjwk.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pjq *PublicJWKQuery) OnlyIDX(ctx context.Context) int {
	id, err := pjq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PublicJWKs.
func (pjq *PublicJWKQuery) All(ctx context.Context) ([]*PublicJWK, error) {
	ctx = setContextOp(ctx, pjq.ctx, "All")
	if err := pjq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PublicJWK, *PublicJWKQuery]()
	return withInterceptors[[]*PublicJWK](ctx, pjq, qr, pjq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pjq *PublicJWKQuery) AllX(ctx context.Context) []*PublicJWK {
	nodes, err := pjq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PublicJWK IDs.
func (pjq *PublicJWKQuery) IDs(ctx context.Context) (ids []int, err error) {
	if pjq.ctx.Unique == nil && pjq.path != nil {
		pjq.Unique(true)
	}
	ctx = setContextOp(ctx, pjq.ctx, "IDs")
	if err = pjq.Select(publicjwk.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pjq *PublicJWKQuery) IDsX(ctx context.Context) []int {
	ids, err := pjq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pjq *PublicJWKQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pjq.ctx, "Count")
	if err := pjq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pjq, querierCount[*PublicJWKQuery](), pjq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pjq *PublicJWKQuery) CountX(ctx context.Context) int {
	count, err := pjq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pjq *PublicJWKQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pjq.ctx, "Exist")
	switch _, err := pjq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pjq *PublicJWKQuery) ExistX(ctx context.Context) bool {
	exist, err := pjq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PublicJWKQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pjq *PublicJWKQuery) Clone() *PublicJWKQuery {
	if pjq == nil {
		return nil
	}
	return &PublicJWKQuery{
		config:     pjq.config,
		ctx:        pjq.ctx.Clone(),
		order:      append([]publicjwk.OrderOption{}, pjq.order...),
		inters:     append([]Interceptor{}, pjq.inters...),
		predicates: append([]predicate.PublicJWK{}, pjq.predicates...),
		// clone intermediate query.
		sql:  pjq.sql.Clone(),
		path: pjq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Sid string `json:"sid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PublicJWK.Query().
//		GroupBy(publicjwk.FieldSid).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (pjq *PublicJWKQuery) GroupBy(field string, fields ...string) *PublicJWKGroupBy {
	pjq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PublicJWKGroupBy{build: pjq}
	grbuild.flds = &pjq.ctx.Fields
	grbuild.label = publicjwk.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Sid string `json:"sid,omitempty"`
//	}
//
//	client.PublicJWK.Query().
//		Select(publicjwk.FieldSid).
//		Scan(ctx, &v)
func (pjq *PublicJWKQuery) Select(fields ...string) *PublicJWKSelect {
	pjq.ctx.Fields = append(pjq.ctx.Fields, fields...)
	sbuild := &PublicJWKSelect{PublicJWKQuery: pjq}
	sbuild.label = publicjwk.Label
	sbuild.flds, sbuild.scan = &pjq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PublicJWKSelect configured with the given aggregations.
func (pjq *PublicJWKQuery) Aggregate(fns ...AggregateFunc) *PublicJWKSelect {
	return pjq.Select().Aggregate(fns...)
}

func (pjq *PublicJWKQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pjq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pjq); err != nil {
				return err
			}
		}
	}
	for _, f := range pjq.ctx.Fields {
		if !publicjwk.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pjq.path != nil {
		prev, err := pjq.path(ctx)
		if err != nil {
			return err
		}
		pjq.sql = prev
	}
	return nil
}

func (pjq *PublicJWKQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PublicJWK, error) {
	var (
		nodes = []*PublicJWK{}
		_spec = pjq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PublicJWK).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PublicJWK{config: pjq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(pjq.modifiers) > 0 {
		_spec.Modifiers = pjq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pjq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	for i := range pjq.loadTotal {
		if err := pjq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pjq *PublicJWKQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pjq.querySpec()
	if len(pjq.modifiers) > 0 {
		_spec.Modifiers = pjq.modifiers
	}
	_spec.Node.Columns = pjq.ctx.Fields
	if len(pjq.ctx.Fields) > 0 {
		_spec.Unique = pjq.ctx.Unique != nil && *pjq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pjq.driver, _spec)
}

func (pjq *PublicJWKQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(publicjwk.Table, publicjwk.Columns, sqlgraph.NewFieldSpec(publicjwk.FieldID, field.TypeInt))
	_spec.From = pjq.sql
	if unique := pjq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pjq.path != nil {
		_spec.Unique = true
	}
	if fields := pjq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, publicjwk.FieldID)
		for i := range fields {
			if fields[i] != publicjwk.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pjq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pjq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pjq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pjq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pjq *PublicJWKQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pjq.driver.Dialect())
	t1 := builder.Table(publicjwk.Table)
	columns := pjq.ctx.Fields
	if len(columns) == 0 {
		columns = publicjwk.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pjq.sql != nil {
		selector = pjq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pjq.ctx.Unique != nil && *pjq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pjq.predicates {
		p(selector)
	}
	for _, p := range pjq.order {
		p(selector)
	}
	if offset := pjq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pjq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PublicJWKGroupBy is the group-by builder for PublicJWK entities.
type PublicJWKGroupBy struct {
	selector
	build *PublicJWKQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pjgb *PublicJWKGroupBy) Aggregate(fns ...AggregateFunc) *PublicJWKGroupBy {
	pjgb.fns = append(pjgb.fns, fns...)
	return pjgb
}

// Scan applies the selector query and scans the result into the given value.
func (pjgb *PublicJWKGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pjgb.build.ctx, "GroupBy")
	if err := pjgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PublicJWKQuery, *PublicJWKGroupBy](ctx, pjgb.build, pjgb, pjgb.build.inters, v)
}

func (pjgb *PublicJWKGroupBy) sqlScan(ctx context.Context, root *PublicJWKQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pjgb.fns))
	for _, fn := range pjgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pjgb.flds)+len(pjgb.fns))
		for _, f := range *pjgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pjgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pjgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PublicJWKSelect is the builder for selecting fields of PublicJWK entities.
type PublicJWKSelect struct {
	*PublicJWKQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pjs *PublicJWKSelect) Aggregate(fns ...AggregateFunc) *PublicJWKSelect {
	pjs.fns = append(pjs.fns, fns...)
	return pjs
}

// Scan applies the selector query and scans the result into the given value.
func (pjs *PublicJWKSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pjs.ctx, "Select")
	if err := pjs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PublicJWKQuery, *PublicJWKSelect](ctx, pjs.PublicJWKQuery, pjs, pjs.inters, v)
}

func (pjs *PublicJWKSelect) sqlScan(ctx context.Context, root *PublicJWKQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pjs.fns))
	for _, fn := range pjs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pjs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pjs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
