// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/koalatea/authserver/server/ent/predicate"
	"github.com/koalatea/authserver/server/ent/publicjwkset"
)

// PublicJWKSetQuery is the builder for querying PublicJWKSet entities.
type PublicJWKSetQuery struct {
	config
	ctx        *QueryContext
	order      []publicjwkset.OrderOption
	inters     []Interceptor
	predicates []predicate.PublicJWKSet
	modifiers  []func(*sql.Selector)
	loadTotal  []func(context.Context, []*PublicJWKSet) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PublicJWKSetQuery builder.
func (pjsq *PublicJWKSetQuery) Where(ps ...predicate.PublicJWKSet) *PublicJWKSetQuery {
	pjsq.predicates = append(pjsq.predicates, ps...)
	return pjsq
}

// Limit the number of records to be returned by this query.
func (pjsq *PublicJWKSetQuery) Limit(limit int) *PublicJWKSetQuery {
	pjsq.ctx.Limit = &limit
	return pjsq
}

// Offset to start from.
func (pjsq *PublicJWKSetQuery) Offset(offset int) *PublicJWKSetQuery {
	pjsq.ctx.Offset = &offset
	return pjsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pjsq *PublicJWKSetQuery) Unique(unique bool) *PublicJWKSetQuery {
	pjsq.ctx.Unique = &unique
	return pjsq
}

// Order specifies how the records should be ordered.
func (pjsq *PublicJWKSetQuery) Order(o ...publicjwkset.OrderOption) *PublicJWKSetQuery {
	pjsq.order = append(pjsq.order, o...)
	return pjsq
}

// First returns the first PublicJWKSet entity from the query.
// Returns a *NotFoundError when no PublicJWKSet was found.
func (pjsq *PublicJWKSetQuery) First(ctx context.Context) (*PublicJWKSet, error) {
	nodes, err := pjsq.Limit(1).All(setContextOp(ctx, pjsq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{publicjwkset.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pjsq *PublicJWKSetQuery) FirstX(ctx context.Context) *PublicJWKSet {
	node, err := pjsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PublicJWKSet ID from the query.
// Returns a *NotFoundError when no PublicJWKSet ID was found.
func (pjsq *PublicJWKSetQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pjsq.Limit(1).IDs(setContextOp(ctx, pjsq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{publicjwkset.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pjsq *PublicJWKSetQuery) FirstIDX(ctx context.Context) int {
	id, err := pjsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PublicJWKSet entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PublicJWKSet entity is found.
// Returns a *NotFoundError when no PublicJWKSet entities are found.
func (pjsq *PublicJWKSetQuery) Only(ctx context.Context) (*PublicJWKSet, error) {
	nodes, err := pjsq.Limit(2).All(setContextOp(ctx, pjsq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{publicjwkset.Label}
	default:
		return nil, &NotSingularError{publicjwkset.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pjsq *PublicJWKSetQuery) OnlyX(ctx context.Context) *PublicJWKSet {
	node, err := pjsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PublicJWKSet ID in the query.
// Returns a *NotSingularError when more than one PublicJWKSet ID is found.
// Returns a *NotFoundError when no entities are found.
func (pjsq *PublicJWKSetQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pjsq.Limit(2).IDs(setContextOp(ctx, pjsq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{publicjwkset.Label}
	default:
		err = &NotSingularError{publicjwkset.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pjsq *PublicJWKSetQuery) OnlyIDX(ctx context.Context) int {
	id, err := pjsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PublicJWKSets.
func (pjsq *PublicJWKSetQuery) All(ctx context.Context) ([]*PublicJWKSet, error) {
	ctx = setContextOp(ctx, pjsq.ctx, "All")
	if err := pjsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PublicJWKSet, *PublicJWKSetQuery]()
	return withInterceptors[[]*PublicJWKSet](ctx, pjsq, qr, pjsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pjsq *PublicJWKSetQuery) AllX(ctx context.Context) []*PublicJWKSet {
	nodes, err := pjsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PublicJWKSet IDs.
func (pjsq *PublicJWKSetQuery) IDs(ctx context.Context) (ids []int, err error) {
	if pjsq.ctx.Unique == nil && pjsq.path != nil {
		pjsq.Unique(true)
	}
	ctx = setContextOp(ctx, pjsq.ctx, "IDs")
	if err = pjsq.Select(publicjwkset.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pjsq *PublicJWKSetQuery) IDsX(ctx context.Context) []int {
	ids, err := pjsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pjsq *PublicJWKSetQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pjsq.ctx, "Count")
	if err := pjsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pjsq, querierCount[*PublicJWKSetQuery](), pjsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pjsq *PublicJWKSetQuery) CountX(ctx context.Context) int {
	count, err := pjsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pjsq *PublicJWKSetQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pjsq.ctx, "Exist")
	switch _, err := pjsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pjsq *PublicJWKSetQuery) ExistX(ctx context.Context) bool {
	exist, err := pjsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PublicJWKSetQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pjsq *PublicJWKSetQuery) Clone() *PublicJWKSetQuery {
	if pjsq == nil {
		return nil
	}
	return &PublicJWKSetQuery{
		config:     pjsq.config,
		ctx:        pjsq.ctx.Clone(),
		order:      append([]publicjwkset.OrderOption{}, pjsq.order...),
		inters:     append([]Interceptor{}, pjsq.inters...),
		predicates: append([]predicate.PublicJWKSet{}, pjsq.predicates...),
		// clone intermediate query.
		sql:  pjsq.sql.Clone(),
		path: pjsq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (pjsq *PublicJWKSetQuery) GroupBy(field string, fields ...string) *PublicJWKSetGroupBy {
	pjsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PublicJWKSetGroupBy{build: pjsq}
	grbuild.flds = &pjsq.ctx.Fields
	grbuild.label = publicjwkset.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (pjsq *PublicJWKSetQuery) Select(fields ...string) *PublicJWKSetSelect {
	pjsq.ctx.Fields = append(pjsq.ctx.Fields, fields...)
	sbuild := &PublicJWKSetSelect{PublicJWKSetQuery: pjsq}
	sbuild.label = publicjwkset.Label
	sbuild.flds, sbuild.scan = &pjsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PublicJWKSetSelect configured with the given aggregations.
func (pjsq *PublicJWKSetQuery) Aggregate(fns ...AggregateFunc) *PublicJWKSetSelect {
	return pjsq.Select().Aggregate(fns...)
}

func (pjsq *PublicJWKSetQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pjsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pjsq); err != nil {
				return err
			}
		}
	}
	for _, f := range pjsq.ctx.Fields {
		if !publicjwkset.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pjsq.path != nil {
		prev, err := pjsq.path(ctx)
		if err != nil {
			return err
		}
		pjsq.sql = prev
	}
	return nil
}

func (pjsq *PublicJWKSetQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PublicJWKSet, error) {
	var (
		nodes = []*PublicJWKSet{}
		_spec = pjsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PublicJWKSet).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PublicJWKSet{config: pjsq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(pjsq.modifiers) > 0 {
		_spec.Modifiers = pjsq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pjsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	for i := range pjsq.loadTotal {
		if err := pjsq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (pjsq *PublicJWKSetQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pjsq.querySpec()
	if len(pjsq.modifiers) > 0 {
		_spec.Modifiers = pjsq.modifiers
	}
	_spec.Node.Columns = pjsq.ctx.Fields
	if len(pjsq.ctx.Fields) > 0 {
		_spec.Unique = pjsq.ctx.Unique != nil && *pjsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pjsq.driver, _spec)
}

func (pjsq *PublicJWKSetQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(publicjwkset.Table, publicjwkset.Columns, sqlgraph.NewFieldSpec(publicjwkset.FieldID, field.TypeInt))
	_spec.From = pjsq.sql
	if unique := pjsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pjsq.path != nil {
		_spec.Unique = true
	}
	if fields := pjsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, publicjwkset.FieldID)
		for i := range fields {
			if fields[i] != publicjwkset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pjsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pjsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pjsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pjsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pjsq *PublicJWKSetQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pjsq.driver.Dialect())
	t1 := builder.Table(publicjwkset.Table)
	columns := pjsq.ctx.Fields
	if len(columns) == 0 {
		columns = publicjwkset.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pjsq.sql != nil {
		selector = pjsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pjsq.ctx.Unique != nil && *pjsq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pjsq.predicates {
		p(selector)
	}
	for _, p := range pjsq.order {
		p(selector)
	}
	if offset := pjsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pjsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PublicJWKSetGroupBy is the group-by builder for PublicJWKSet entities.
type PublicJWKSetGroupBy struct {
	selector
	build *PublicJWKSetQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pjsgb *PublicJWKSetGroupBy) Aggregate(fns ...AggregateFunc) *PublicJWKSetGroupBy {
	pjsgb.fns = append(pjsgb.fns, fns...)
	return pjsgb
}

// Scan applies the selector query and scans the result into the given value.
func (pjsgb *PublicJWKSetGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pjsgb.build.ctx, "GroupBy")
	if err := pjsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PublicJWKSetQuery, *PublicJWKSetGroupBy](ctx, pjsgb.build, pjsgb, pjsgb.build.inters, v)
}

func (pjsgb *PublicJWKSetGroupBy) sqlScan(ctx context.Context, root *PublicJWKSetQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pjsgb.fns))
	for _, fn := range pjsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pjsgb.flds)+len(pjsgb.fns))
		for _, f := range *pjsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pjsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pjsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PublicJWKSetSelect is the builder for selecting fields of PublicJWKSet entities.
type PublicJWKSetSelect struct {
	*PublicJWKSetQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pjss *PublicJWKSetSelect) Aggregate(fns ...AggregateFunc) *PublicJWKSetSelect {
	pjss.fns = append(pjss.fns, fns...)
	return pjss
}

// Scan applies the selector query and scans the result into the given value.
func (pjss *PublicJWKSetSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pjss.ctx, "Select")
	if err := pjss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PublicJWKSetQuery, *PublicJWKSetSelect](ctx, pjss.PublicJWKSetQuery, pjss, pjss.inters, v)
}

func (pjss *PublicJWKSetSelect) sqlScan(ctx context.Context, root *PublicJWKSetQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pjss.fns))
	for _, fn := range pjss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pjss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pjss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
