// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/koalatea/authserver/server/ent/predicate"
	"github.com/koalatea/authserver/server/ent/publicjwkset"
)

// PublicJWKSetUpdate is the builder for updating PublicJWKSet entities.
type PublicJWKSetUpdate struct {
	config
	hooks    []Hook
	mutation *PublicJWKSetMutation
}

// Where appends a list predicates to the PublicJWKSetUpdate builder.
func (pjsu *PublicJWKSetUpdate) Where(ps ...predicate.PublicJWKSet) *PublicJWKSetUpdate {
	pjsu.mutation.Where(ps...)
	return pjsu
}

// Mutation returns the PublicJWKSetMutation object of the builder.
func (pjsu *PublicJWKSetUpdate) Mutation() *PublicJWKSetMutation {
	return pjsu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pjsu *PublicJWKSetUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pjsu.hooks) == 0 {
		affected, err = pjsu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PublicJWKSetMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pjsu.mutation = mutation
			affected, err = pjsu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pjsu.hooks) - 1; i >= 0; i-- {
			if pjsu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pjsu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pjsu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pjsu *PublicJWKSetUpdate) SaveX(ctx context.Context) int {
	affected, err := pjsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pjsu *PublicJWKSetUpdate) Exec(ctx context.Context) error {
	_, err := pjsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pjsu *PublicJWKSetUpdate) ExecX(ctx context.Context) {
	if err := pjsu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pjsu *PublicJWKSetUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   publicjwkset.Table,
			Columns: publicjwkset.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: publicjwkset.FieldID,
			},
		},
	}
	if ps := pjsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pjsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{publicjwkset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// PublicJWKSetUpdateOne is the builder for updating a single PublicJWKSet entity.
type PublicJWKSetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PublicJWKSetMutation
}

// Mutation returns the PublicJWKSetMutation object of the builder.
func (pjsuo *PublicJWKSetUpdateOne) Mutation() *PublicJWKSetMutation {
	return pjsuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pjsuo *PublicJWKSetUpdateOne) Select(field string, fields ...string) *PublicJWKSetUpdateOne {
	pjsuo.fields = append([]string{field}, fields...)
	return pjsuo
}

// Save executes the query and returns the updated PublicJWKSet entity.
func (pjsuo *PublicJWKSetUpdateOne) Save(ctx context.Context) (*PublicJWKSet, error) {
	var (
		err  error
		node *PublicJWKSet
	)
	if len(pjsuo.hooks) == 0 {
		node, err = pjsuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PublicJWKSetMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pjsuo.mutation = mutation
			node, err = pjsuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pjsuo.hooks) - 1; i >= 0; i-- {
			if pjsuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pjsuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, pjsuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*PublicJWKSet)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from PublicJWKSetMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (pjsuo *PublicJWKSetUpdateOne) SaveX(ctx context.Context) *PublicJWKSet {
	node, err := pjsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pjsuo *PublicJWKSetUpdateOne) Exec(ctx context.Context) error {
	_, err := pjsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pjsuo *PublicJWKSetUpdateOne) ExecX(ctx context.Context) {
	if err := pjsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pjsuo *PublicJWKSetUpdateOne) sqlSave(ctx context.Context) (_node *PublicJWKSet, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   publicjwkset.Table,
			Columns: publicjwkset.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: publicjwkset.FieldID,
			},
		},
	}
	id, ok := pjsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PublicJWKSet.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pjsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, publicjwkset.FieldID)
		for _, f := range fields {
			if !publicjwkset.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != publicjwkset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pjsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &PublicJWKSet{config: pjsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pjsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{publicjwkset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
