// Code generated by ent, DO NOT EDIT.

package oauthrefreshtoken

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the oauthrefreshtoken type in the database.
	Label = "oauth_refresh_token"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSignature holds the string denoting the signature field in the database.
	FieldSignature = "signature"
	// EdgeSession holds the string denoting the session edge name in mutations.
	EdgeSession = "session"
	// Table holds the table name of the oauthrefreshtoken in the database.
	Table = "oauth_refresh_tokens"
	// SessionTable is the table that holds the session relation/edge.
	SessionTable = "oauth_refresh_tokens"
	// SessionInverseTable is the table name for the OAuthSession entity.
	// It exists in this package in order to avoid circular dependency with the "oauthsession" package.
	SessionInverseTable = "oauth_sessions"
	// SessionColumn is the table column denoting the session relation/edge.
	SessionColumn = "oauth_refresh_token_session"
)

// Columns holds all SQL columns for oauthrefreshtoken fields.
var Columns = []string{
	FieldID,
	FieldSignature,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "oauth_refresh_tokens"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"oauth_refresh_token_session",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the OAuthRefreshToken queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySignature orders the results by the signature field.
func BySignature(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSignature, opts...).ToFunc()
}

// BySessionField orders the results by session field.
func BySessionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSessionStep(), sql.OrderByField(field, opts...))
	}
}
func newSessionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SessionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, SessionTable, SessionColumn),
	)
}
