// Code generated by ent, DO NOT EDIT.

package oauthaccesstoken

const (
	// Label holds the string label denoting the oauthaccesstoken type in the database.
	Label = "oauth_access_token"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSignature holds the string denoting the signature field in the database.
	FieldSignature = "signature"
	// EdgeSession holds the string denoting the session edge name in mutations.
	EdgeSession = "session"
	// Table holds the table name of the oauthaccesstoken in the database.
	Table = "oauth_access_tokens"
	// SessionTable is the table that holds the session relation/edge.
	SessionTable = "oauth_access_tokens"
	// SessionInverseTable is the table name for the OAuthSession entity.
	// It exists in this package in order to avoid circular dependency with the "oauthsession" package.
	SessionInverseTable = "oauth_sessions"
	// SessionColumn is the table column denoting the session relation/edge.
	SessionColumn = "oauth_access_token_session"
)

// Columns holds all SQL columns for oauthaccesstoken fields.
var Columns = []string{
	FieldID,
	FieldSignature,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "oauth_access_tokens"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"oauth_access_token_session",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
