name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.0-rc.1
    - name: ⚡ Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          ~\AppData\Local\go-build
        key: ubuntu-latest-authserver-go-1.18.0-rc.1-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ubuntu-latest-authserver-go-1.18.0-rc.1- 
    - name: Build
      run: go build -v -o ./build/server ./server
    - name: Test
      run: go test -v ./server/...